/* basic.c - generated by tools/json_to_mode.py */
#include <mode/user/basic.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_value;
    uint8_t  max_value;
    uint8_t  curve_mode;
    uint32_t color_on;
    uint32_t color_off;
    /* runtime state (reset in init) */
    uint8_t  current;
    uint8_t  target;
    uint8_t  rate;
    uint8_t  timer_accum;
} Fader;

/* Rate colors: instant=white  1-bar=green  4-bar=yellow  16-bar=red */
static const uint32_t RATE_COLORS[4] = { 0xFFFFFF, 0x22CC44, 0xCCCC00, 0xCC2222 };

static void update_fader_leds(Fader *f) {
    uint8_t throw_start = f->curve_mode ? 1 : 0;
    uint8_t throw_count = f->length - throw_start;
    uint8_t fill = 0;
    uint8_t range = f->max_value - f->min_value;
    if (range > 0 && throw_count > 1) {
        fill = (uint8_t)((uint16_t)(f->current - f->min_value)
                         * (throw_count - 1) / range);
    } else if (f->current >= f->max_value) {
        fill = throw_count > 0 ? throw_count - 1 : 0;
    }
    for (uint8_t i = 0; i < throw_count; i++) {
        uint8_t pad = (uint8_t)((int)f->anchor_xy
                                + (throw_start + i) * f->pad_step);
        set_led(pad, (i <= fill) ? f->color_on : f->color_off);
    }
    if (f->curve_mode) {
        set_led(f->anchor_xy, RATE_COLORS[f->rate]);
    }
}

/* Timer divisors per rate (tune if timer freq differs from ~360 Hz): */
/* rate 0=instant  1=~1 bar@120bpm  2=~4 bars  3=~16 bars           */
static const uint8_t  TIMER_DIV[4]   = {  0,   6,  24,  96 };

#define N_FADERS 6
static Fader faders[N_FADERS] = {
    {
        .anchor_xy  = 11,
        .length     = 9,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .curve_mode = 1,
        .color_on   = 0x1FCE26,
        .color_off  = 0xC1F9CD,
    },
    {
        .anchor_xy  = 12,
        .length     = 9,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .curve_mode = 1,
        .color_on   = 0xFF0100,
        .color_off  = 0xFF918C,
    },
    {
        .anchor_xy  = 13,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .curve_mode = 0,
        .color_on   = 0x33CCCC,
        .color_off  = 0x0A2222,
    },
    {
        .anchor_xy  = 14,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .curve_mode = 0,
        .color_on   = 0x33CCCC,
        .color_off  = 0x0A2222,
    },
    {
        .anchor_xy  = 53,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .curve_mode = 0,
        .color_on   = 0x33CCCC,
        .color_off  = 0x0A2222,
    },
    {
        .anchor_xy  = 54,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .curve_mode = 0,
        .color_on   = 0x33CCCC,
        .color_off  = 0x0A2222,
    },
};

void basic_init() {
    set_led(85, 0x0A1533);
    set_led(86, 0x0A1533);
    set_led(87, 0x0A1533);
    set_led(88, 0x0A1533);
    set_led(93, 0x0A2211);
    set_led(94, 0x331100);
    for (uint8_t i = 0; i < N_FADERS; i++) {
        faders[i].current     = faders[i].min_value;
        faders[i].target      = faders[i].min_value;
        faders[i].rate        = 0;
        faders[i].timer_accum = 0;
        update_fader_leds(&faders[i]);
        driver_send_midi(1,
            (uint8_t[]){(uint8_t)(0xB0 | faders[i].channel),
                        faders[i].cc, faders[i].min_value}, 3);
    }
}

void basic_timer_event() {
    for (uint8_t i = 0; i < N_FADERS; i++) {
        Fader *f = &faders[i];
        if (f->rate == 0 || f->current == f->target) continue;
        if (++f->timer_accum < TIMER_DIV[f->rate]) continue;
        f->timer_accum = 0;
        if (f->current < f->target) f->current++;
        else                        f->current--;
        update_fader_leds(f);
        driver_send_midi(1,
            (uint8_t[]){(uint8_t)(0xB0 | f->channel), f->cc, f->current}, 3);
    }
}

void basic_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 85:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 60, value}, 3);
                set_led(85, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 60, 0}, 3);
                set_led(85, 0x0A1533);
            }
            break;
        case 86:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 60, value}, 3);
                set_led(86, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 60, 0}, 3);
                set_led(86, 0x0A1533);
            }
            break;
        case 87:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 60, value}, 3);
                set_led(87, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 60, 0}, 3);
                set_led(87, 0x0A1533);
            }
            break;
        case 88:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 60, value}, 3);
                set_led(88, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 60, 0}, 3);
                set_led(88, 0x0A1533);
            }
            break;
        case 93:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0XB0, 0, 127}, 3);
                set_led(93, 0x44CC66);
            } else {
                driver_send_midi(1, (uint8_t[]){0XB0, 0, 0}, 3);
                set_led(93, 0x0A2211);
            }
            break;
        case 94:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0XC0, 0, 0}, 3);
                set_led(94, 0xFF6633);
            }
            break;
        case 11:
            if (type) {
                faders[0].rate = (faders[0].rate + 1) % 4;
                faders[0].timer_accum = 0;
                set_led(11, RATE_COLORS[faders[0].rate]);
            }
            break;
        case 12:
            if (type) {
                faders[1].rate = (faders[1].rate + 1) % 4;
                faders[1].timer_accum = 0;
                set_led(12, RATE_COLORS[faders[1].rate]);
            }
            break;
        case 13:
            if (type) {
                faders[2].current     = 0;
                faders[2].target      = 0;
                faders[2].timer_accum = 0;
                update_fader_leds(&faders[2]);
                driver_send_midi(1, (uint8_t[]){0XB0, 0, 0}, 3);
            }
            break;
        case 14:
            if (type) {
                faders[3].current     = 0;
                faders[3].target      = 0;
                faders[3].timer_accum = 0;
                update_fader_leds(&faders[3]);
                driver_send_midi(1, (uint8_t[]){0XB0, 0, 0}, 3);
            }
            break;
        case 21:
            if (type) {
                faders[0].current     = 0;
                faders[0].target      = 0;
                faders[0].timer_accum = 0;
                update_fader_leds(&faders[0]);
                driver_send_midi(1, (uint8_t[]){0XB0, 0, 0}, 3);
            }
            break;
        case 22:
            if (type) {
                faders[1].current     = 0;
                faders[1].target      = 0;
                faders[1].timer_accum = 0;
                update_fader_leds(&faders[1]);
                driver_send_midi(1, (uint8_t[]){0XB0, 0, 0}, 3);
            }
            break;
        case 23:
            if (type) {
                faders[2].target = 42;
                if (faders[2].rate == 0) {
                    faders[2].current = 42;
                    update_fader_leds(&faders[2]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 42}, 3);
                }
            }
            break;
        case 24:
            if (type) {
                faders[3].target = 42;
                if (faders[3].rate == 0) {
                    faders[3].current = 42;
                    update_fader_leds(&faders[3]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 42}, 3);
                }
            }
            break;
        case 31:
            if (type) {
                faders[0].target = 18;
                if (faders[0].rate == 0) {
                    faders[0].current = 18;
                    update_fader_leds(&faders[0]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 18}, 3);
                }
            }
            break;
        case 32:
            if (type) {
                faders[1].target = 18;
                if (faders[1].rate == 0) {
                    faders[1].current = 18;
                    update_fader_leds(&faders[1]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 18}, 3);
                }
            }
            break;
        case 33:
            if (type) {
                faders[2].target = 84;
                if (faders[2].rate == 0) {
                    faders[2].current = 84;
                    update_fader_leds(&faders[2]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 84}, 3);
                }
            }
            break;
        case 34:
            if (type) {
                faders[3].target = 84;
                if (faders[3].rate == 0) {
                    faders[3].current = 84;
                    update_fader_leds(&faders[3]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 84}, 3);
                }
            }
            break;
        case 41:
            if (type) {
                faders[0].target = 36;
                if (faders[0].rate == 0) {
                    faders[0].current = 36;
                    update_fader_leds(&faders[0]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 36}, 3);
                }
            }
            break;
        case 42:
            if (type) {
                faders[1].target = 36;
                if (faders[1].rate == 0) {
                    faders[1].current = 36;
                    update_fader_leds(&faders[1]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 36}, 3);
                }
            }
            break;
        case 43:
            if (type) {
                faders[2].target = 127;
                if (faders[2].rate == 0) {
                    faders[2].current = 127;
                    update_fader_leds(&faders[2]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 127}, 3);
                }
            }
            break;
        case 44:
            if (type) {
                faders[3].target = 127;
                if (faders[3].rate == 0) {
                    faders[3].current = 127;
                    update_fader_leds(&faders[3]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 127}, 3);
                }
            }
            break;
        case 51:
            if (type) {
                faders[0].target = 54;
                if (faders[0].rate == 0) {
                    faders[0].current = 54;
                    update_fader_leds(&faders[0]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 54}, 3);
                }
            }
            break;
        case 52:
            if (type) {
                faders[1].target = 54;
                if (faders[1].rate == 0) {
                    faders[1].current = 54;
                    update_fader_leds(&faders[1]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 54}, 3);
                }
            }
            break;
        case 53:
            if (type) {
                faders[4].current     = 0;
                faders[4].target      = 0;
                faders[4].timer_accum = 0;
                update_fader_leds(&faders[4]);
                driver_send_midi(1, (uint8_t[]){0XB0, 0, 0}, 3);
            }
            break;
        case 54:
            if (type) {
                faders[5].current     = 0;
                faders[5].target      = 0;
                faders[5].timer_accum = 0;
                update_fader_leds(&faders[5]);
                driver_send_midi(1, (uint8_t[]){0XB0, 0, 0}, 3);
            }
            break;
        case 61:
            if (type) {
                faders[0].target = 72;
                if (faders[0].rate == 0) {
                    faders[0].current = 72;
                    update_fader_leds(&faders[0]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 72}, 3);
                }
            }
            break;
        case 62:
            if (type) {
                faders[1].target = 72;
                if (faders[1].rate == 0) {
                    faders[1].current = 72;
                    update_fader_leds(&faders[1]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 72}, 3);
                }
            }
            break;
        case 63:
            if (type) {
                faders[4].target = 42;
                if (faders[4].rate == 0) {
                    faders[4].current = 42;
                    update_fader_leds(&faders[4]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 42}, 3);
                }
            }
            break;
        case 64:
            if (type) {
                faders[5].target = 42;
                if (faders[5].rate == 0) {
                    faders[5].current = 42;
                    update_fader_leds(&faders[5]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 42}, 3);
                }
            }
            break;
        case 71:
            if (type) {
                faders[0].target = 90;
                if (faders[0].rate == 0) {
                    faders[0].current = 90;
                    update_fader_leds(&faders[0]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 90}, 3);
                }
            }
            break;
        case 72:
            if (type) {
                faders[1].target = 90;
                if (faders[1].rate == 0) {
                    faders[1].current = 90;
                    update_fader_leds(&faders[1]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 90}, 3);
                }
            }
            break;
        case 73:
            if (type) {
                faders[4].target = 84;
                if (faders[4].rate == 0) {
                    faders[4].current = 84;
                    update_fader_leds(&faders[4]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 84}, 3);
                }
            }
            break;
        case 74:
            if (type) {
                faders[5].target = 84;
                if (faders[5].rate == 0) {
                    faders[5].current = 84;
                    update_fader_leds(&faders[5]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 84}, 3);
                }
            }
            break;
        case 81:
            if (type) {
                faders[0].target = 108;
                if (faders[0].rate == 0) {
                    faders[0].current = 108;
                    update_fader_leds(&faders[0]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 108}, 3);
                }
            }
            break;
        case 82:
            if (type) {
                faders[1].target = 108;
                if (faders[1].rate == 0) {
                    faders[1].current = 108;
                    update_fader_leds(&faders[1]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 108}, 3);
                }
            }
            break;
        case 83:
            if (type) {
                faders[4].target = 127;
                if (faders[4].rate == 0) {
                    faders[4].current = 127;
                    update_fader_leds(&faders[4]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 127}, 3);
                }
            }
            break;
        case 84:
            if (type) {
                faders[5].target = 127;
                if (faders[5].rate == 0) {
                    faders[5].current = 127;
                    update_fader_leds(&faders[5]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 127}, 3);
                }
            }
            break;
        case 91:
            if (type) {
                faders[0].target = 127;
                if (faders[0].rate == 0) {
                    faders[0].current = 127;
                    update_fader_leds(&faders[0]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 127}, 3);
                }
            }
            break;
        case 92:
            if (type) {
                faders[1].target = 127;
                if (faders[1].rate == 0) {
                    faders[1].current = 127;
                    update_fader_leds(&faders[1]);
                    driver_send_midi(1, (uint8_t[]){0XB0, 0, 127}, 3);
                }
            }
            break;
        default: break;
    }
}

void basic_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port; (void)status; (void)d1; (void)d2;
}

void basic_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
