/* demo.c - generated by tools/json_to_mode.py */
#include <mode/user/demo.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>

static uint8_t toggle[100];

void demo_init() {
    for (int i = 0; i < 100; i++) toggle[i] = 0;
    set_led(11, 0x220022);
    set_led(12, 0x220022);
    set_led(13, 0x220022);
    set_led(14, 0x220022);
    set_led(19, 0x1A1A00);
    set_led(59, 0x331100);
    set_led(69, 0x331100);
    set_led(71, 0x041533);
    set_led(72, 0x041533);
    set_led(73, 0x041533);
    set_led(74, 0x041533);
    set_led(75, 0x041533);
    set_led(76, 0x041533);
    set_led(77, 0x041533);
    set_led(78, 0x041533);
    set_led(79, 0x0A2211);
    set_led(81, 0x0A1533);
    set_led(82, 0x0A1533);
    set_led(83, 0x0A1533);
    set_led(84, 0x0A1533);
    set_led(85, 0x0A1533);
    set_led(86, 0x0A1533);
    set_led(87, 0x0A1533);
    set_led(88, 0x0A1533);
    set_led(89, 0x0A2211);
}

void demo_timer_event() {
}

void demo_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 11:
            if (type) {
                toggle[11] ^= 1;
                if (toggle[11]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 20, 127}, 3);
                    set_led(11, 0xE039E0);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 20, 0}, 3);
                    set_led(11, 0x220022);
                }
            }
            break;
        case 12:
            if (type) {
                toggle[12] ^= 1;
                if (toggle[12]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 21, 127}, 3);
                    set_led(12, 0xE039E0);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 21, 0}, 3);
                    set_led(12, 0x220022);
                }
            }
            break;
        case 13:
            if (type) {
                toggle[13] ^= 1;
                if (toggle[13]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 22, 127}, 3);
                    set_led(13, 0xE039E0);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 22, 0}, 3);
                    set_led(13, 0x220022);
                }
            }
            break;
        case 14:
            if (type) {
                toggle[14] ^= 1;
                if (toggle[14]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 23, 127}, 3);
                    set_led(14, 0xE039E0);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 23, 0}, 3);
                    set_led(14, 0x220022);
                }
            }
            break;
        case 19:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0XB0, 64, 127}, 3);
                set_led(19, 0xF3F306);
            } else {
                driver_send_midi(1, (uint8_t[]){0XB0, 64, 0}, 3);
                set_led(19, 0x1A1A00);
            }
            break;
        case 59:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0XC0, 1, 0}, 3);
                set_led(59, 0xFF6633);
            }
            break;
        case 69:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0XC0, 0, 0}, 3);
                set_led(69, 0xFF6633);
            }
            break;
        case 71:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 48, value}, 3);
                set_led(71, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 48, 0}, 3);
                set_led(71, 0x041533);
            }
            break;
        case 72:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 50, value}, 3);
                set_led(72, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 50, 0}, 3);
                set_led(72, 0x041533);
            }
            break;
        case 73:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 52, value}, 3);
                set_led(73, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 52, 0}, 3);
                set_led(73, 0x041533);
            }
            break;
        case 74:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 53, value}, 3);
                set_led(74, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 53, 0}, 3);
                set_led(74, 0x041533);
            }
            break;
        case 75:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 55, value}, 3);
                set_led(75, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 55, 0}, 3);
                set_led(75, 0x041533);
            }
            break;
        case 76:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 57, value}, 3);
                set_led(76, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 57, 0}, 3);
                set_led(76, 0x041533);
            }
            break;
        case 77:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 59, value}, 3);
                set_led(77, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 59, 0}, 3);
                set_led(77, 0x041533);
            }
            break;
        case 78:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 60, value}, 3);
                set_led(78, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 60, 0}, 3);
                set_led(78, 0x041533);
            }
            break;
        case 79:
            if (type) {
                toggle[79] ^= 1;
                if (toggle[79]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 65, 127}, 3);
                    set_led(79, 0x04FF89);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 65, 0}, 3);
                    set_led(79, 0x0A2211);
                }
            }
            break;
        case 81:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 60, value}, 3);
                set_led(81, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 60, 0}, 3);
                set_led(81, 0x0A1533);
            }
            break;
        case 82:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 62, value}, 3);
                set_led(82, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 62, 0}, 3);
                set_led(82, 0x0A1533);
            }
            break;
        case 83:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 64, value}, 3);
                set_led(83, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 64, 0}, 3);
                set_led(83, 0x0A1533);
            }
            break;
        case 84:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 65, value}, 3);
                set_led(84, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 65, 0}, 3);
                set_led(84, 0x0A1533);
            }
            break;
        case 85:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 67, value}, 3);
                set_led(85, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 67, 0}, 3);
                set_led(85, 0x0A1533);
            }
            break;
        case 86:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 69, value}, 3);
                set_led(86, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 69, 0}, 3);
                set_led(86, 0x0A1533);
            }
            break;
        case 87:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 71, value}, 3);
                set_led(87, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 71, 0}, 3);
                set_led(87, 0x0A1533);
            }
            break;
        case 88:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 72, value}, 3);
                set_led(88, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 72, 0}, 3);
                set_led(88, 0x0A1533);
            }
            break;
        case 89:
            if (type) {
                toggle[89] ^= 1;
                if (toggle[89]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 64, 127}, 3);
                    set_led(89, 0x04FF89);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 64, 0}, 3);
                    set_led(89, 0x0A2211);
                }
            }
            break;
        default: break;
    }
}

void demo_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port; (void)status; (void)d1; (void)d2;
}

void demo_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
