/* lfo_test.c - generated by tools/json_to_mode.py */
#include <mode/user/lfo_test.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>
#include <utils/cc_state.h>
#include <utils/fader.h>
#include <utils/lfo.h>

static void send_midi3(uint8_t status, uint8_t d1, uint8_t d2) {
    uint8_t buf[3] = { status, d1, d2 };
    driver_send_midi(1, buf, 3);
}

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_value;
    uint8_t  max_value;
    uint32_t color_on;
    uint32_t color_off;
    uint8_t  smooth_group;  /* 0xFF = no group, ticks=1 fallback */
} FaderCfg;

#define N_FADERS 2
static const FaderCfg FADERS[N_FADERS] = {
    {
        .anchor_xy  = 12,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 33,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x33CCCC,
        .color_off  = 0x0A2222,
        .smooth_group = 255,  /* no group, ticks=1 */
    },
    {
        .anchor_xy  = 14,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 44,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0x480000,
        .smooth_group = 255,  /* no group, ticks=1 */
    },
};

__attribute__((section(".cfw_bss"))) static uint8_t fader_display_current[N_FADERS];
__attribute__((section(".cfw_bss"))) static uint8_t fader_fill[N_FADERS];
__attribute__((section(".cfw_bss"))) static uint32_t fader_activated;

static void update_fader_leds(uint8_t fi, uint8_t fill, uint32_t color_on) {
    const FaderCfg *f = &FADERS[fi];
    for (uint8_t i = 0; i < f->length; i++) {
        uint8_t pad = (uint8_t)((int)f->anchor_xy + i * f->pad_step);
        set_led(pad, (i <= fill) ? color_on : f->color_off);
    }
}

static void update_fader_display(uint8_t fi, uint8_t value) {
    const FaderCfg *f = &FADERS[fi];
    fader_display_current[fi] = value;
    fader_activated |= (1u << fi);
    uint32_t col_on = f->color_on;
    if (value < f->min_value) {
        fader_fill[fi] = 0;
        for (uint8_t i = 0; i < f->length; i++)
            set_led((uint8_t)((int)f->anchor_xy + i * f->pad_step), f->color_off);
    } else if (value >= f->max_value) {
        fader_fill[fi] = (uint8_t)(f->length - 1u);
        update_fader_leds(fi, (uint8_t)(f->length - 1u), col_on);
    } else {
        uint8_t best = 0, best_diff = 255;
        for (uint8_t t = 0; t < f->length; t++) {
            uint8_t cv = (t == 0) ? f->min_value :
                         (t >= f->length - 1u) ? f->max_value :
                         (uint8_t)(f->min_value + t * (f->max_value - f->min_value) / (f->length - 1u));
            uint8_t diff = (value >= cv) ? (value - cv) : (cv - value);
            if (diff < best_diff) { best_diff = diff; best = t; }
        }
        fader_fill[fi] = best;
        update_fader_leds(fi, best, col_on);
    }
}

static void handle_fader_cc(uint8_t channel, uint8_t cc, uint8_t value) {
    for (uint8_t fi = 0; fi < N_FADERS; fi++) {
        if (FADERS[fi].channel != channel || FADERS[fi].cc != cc) continue;
        cc_state_set(channel, cc, value);
        update_fader_display(fi, value);
    }
}

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_val;
    uint8_t  max_val;
    uint8_t  start_val;
    uint8_t  rate_channel;
    uint8_t  rate_cc;
    uint16_t rate_min_ticks;
    uint16_t rate_max_ticks;
    uint32_t color_on;
    uint32_t color_off;
} LfoCfg;

#define N_LFOS 1
static const LfoCfg LFOS[N_LFOS] = {
    {
        .anchor_xy      = 11,
        .length         = 8,
        .pad_step       = 10,
        .cc             = 44,
        .channel        = 0,
        .min_val        = 0,
        .max_val        = 127,
        .start_val      = 63,
        .rate_channel   = 0,
        .rate_cc        = 33,
        .rate_min_ticks = 14,
        .rate_max_ticks = 714,
        .color_on       = 0x22FFCC,
        .color_off      = 0x001A16,
    },
};

__attribute__((section(".cfw_bss"))) static uint8_t lfo_display_current[N_LFOS];

static void update_lfo_display(uint8_t li, uint8_t value) {
    const LfoCfg *l = &LFOS[li];
    lfo_display_current[li] = value;
    uint8_t pos = 0;
    if (l->max_val > l->min_val && l->length > 1) {
        uint8_t best = 0, best_diff = 255;
        for (uint8_t t = 0; t < l->length; t++) {
            uint8_t cv = (t == 0) ? l->min_val :
                         (t >= l->length - 1u) ? l->max_val :
                         (uint8_t)(l->min_val + t * (l->max_val - l->min_val) / (l->length - 1u));
            uint8_t diff = (value >= cv) ? (value - cv) : (cv - value);
            if (diff < best_diff) { best_diff = diff; best = t; }
        }
        pos = best;
    }
    for (uint8_t i = 0; i < l->length; i++) {
        uint8_t pad = (uint8_t)((int)l->anchor_xy + i * l->pad_step);
        set_led(pad, (i == pos) ? l->color_on : l->color_off);
    }
}

void lfo_test_init() {
    static uint8_t mode_initialized;
    if (!mode_initialized) {
        for (uint8_t i = 0; i < N_FADERS; i++) {
            fader_display_current[i] = FADERS[i].min_value;
            fader_fill[i] = 0;
            if (cc_state_get(FADERS[i].channel, FADERS[i].cc) == 0xFF)
                cc_state_set(FADERS[i].channel, FADERS[i].cc, 0);
        }
        fader_activated = 0;
        for (uint8_t li = 0; li < N_LFOS; li++) lfo_display_current[li] = 0xFF;
        mode_initialized = 1;
    }
    set_led(49, 0xFF00FF);
    set_led(59, 0xFFDBB7);
    set_led(69, 0xB7FFB7);
    set_led(79, 0xB7B7FF);
    set_led(89, 0xFFB7B7);
    for (uint8_t i = 0; i < N_FADERS; i++) {
        uint8_t gv = cc_state_get(FADERS[i].channel, FADERS[i].cc);
        if (gv != 0xFF) {
            handle_fader_cc(FADERS[i].channel, FADERS[i].cc, gv);
        } else if (fader_activated & (1u << i)) {
            update_fader_leds(i, fader_fill[i], FADERS[i].color_on);
        } else {
            const FaderCfg *f = &FADERS[i];
            for (uint8_t j = 0; j < f->length; j++)
                set_led((uint8_t)((int)f->anchor_xy + j * f->pad_step), f->color_off);
        }
    }
    for (uint8_t li = 0; li < N_LFOS; li++) {
        const LfoCfg *l = &LFOS[li];
        lfo_register(l->channel, l->cc, l->min_val, l->max_val, l->start_val,
                     l->length,
                     l->rate_channel, l->rate_cc, l->rate_min_ticks, l->rate_max_ticks);
        uint8_t cur = lfo_current(l->channel, l->cc);
        update_lfo_display(li, (cur != 0xFF) ? cur : l->start_val);
    }
}

void lfo_test_timer_event() {
    for (uint8_t fi = 0; fi < N_FADERS; fi++) {
        uint8_t cur = fader_current(FADERS[fi].channel, FADERS[fi].cc);
        if (cur == 0xFF)
            cur = cc_state_get(FADERS[fi].channel, FADERS[fi].cc);
        if (cur == 0xFF || cur == fader_display_current[fi]) continue;
        update_fader_display(fi, cur);
    }
    for (uint8_t li = 0; li < N_LFOS; li++) {
        uint8_t cur = lfo_current(LFOS[li].channel, LFOS[li].cc);
        if (cur == 0xFF || cur == lfo_display_current[li]) continue;
        update_lfo_display(li, cur);
    }
}

void lfo_test_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 49:
            if (type) mode_switch(MODE_LFO_TEST);
            break;
        case 59:
            if (type) mode_switch(MODE_MEGA_FADERS);
            break;
        case 69:
            if (type) mode_switch(MODE_D_FADE);
            break;
        case 79:
            if (type) mode_switch(MODE_MIXER2);
            break;
        case 89:
            if (type) mode_switch(MODE_MIXER1);
            break;
        default:
            if (type) {
                for (uint8_t fi = 0; fi < N_FADERS; fi++) {
                    const FaderCfg *f = &FADERS[fi];
                    int16_t delta = (int16_t)index - (int16_t)f->anchor_xy;
                    int8_t  step  = f->pad_step;
                    uint8_t throw_pos;
                    if (step > 0) {
                        if (delta < 0 || delta >= (int16_t)f->length * step || delta % step != 0) continue;
                        throw_pos = (uint8_t)(delta / step);
                    } else {
                        if (delta > 0 || delta <= (int16_t)f->length * step || (-delta) % (-step) != 0) continue;
                        throw_pos = (uint8_t)((-delta) / (-step));
                    }
                    uint8_t val = (throw_pos == 0) ? f->min_value :
                                  (throw_pos >= f->length - 1u) ? f->max_value :
                                  (uint8_t)(f->min_value + throw_pos * (f->max_value - f->min_value) / (f->length - 1u));
                    {
                        uint16_t ticks = 1;
                        fader_fade(f->channel, f->cc, val, ticks);
                        return;
                    }
                }
            }
            break;
    }
    (void)value;
}

void lfo_test_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port;
    if ((status & 0xF0) == 0xB0) {
        uint8_t ch = (uint8_t)(status & 0x0F);
        fader_cancel(ch, d1);
        handle_fader_cc(ch, d1, d2);
    }
}

void lfo_test_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
