/* mega_faders.c - generated by tools/json_to_mode.py */
#include <mode/user/mega_faders.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>
#include <utils/cc_state.h>

static void send_midi3(uint8_t status, uint8_t d1, uint8_t d2) {
    uint8_t buf[3] = { status, d1, d2 };
    driver_send_midi(1, buf, 3);
}

__attribute__((section(".cfw_bss"))) static uint8_t toggle[100];

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_value;
    uint8_t  max_value;
    uint32_t color_on;
    uint32_t color_off;
} FaderCfg;

#define N_FADERS 9
static const FaderCfg FADERS[N_FADERS] = {
    {
        .anchor_xy  = 21,
        .length     = 9,
        .pad_step   = 1,
        .cc         = 11,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0000FF,
        .color_off  = 0xB7B7FF,
    },
    {
        .anchor_xy  = 31,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 32,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 33,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 34,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 35,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 36,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 37,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 38,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
};

__attribute__((section(".cfw_bss"))) static uint8_t fader_current[N_FADERS];
__attribute__((section(".cfw_bss"))) static uint8_t fader_fill[N_FADERS];
__attribute__((section(".cfw_bss"))) static uint32_t fader_activated;

static void update_fader_leds(uint8_t fi, uint8_t fill) {
    const FaderCfg *f = &FADERS[fi];
    for (uint8_t i = 0; i < f->length; i++) {
        uint8_t pad = (uint8_t)((int)f->anchor_xy + i * f->pad_step);
        set_led(pad, (i <= fill) ? f->color_on : f->color_off);
    }
}

static void handle_fader_cc(uint8_t channel, uint8_t cc, uint8_t value) {
    for (uint8_t fi = 0; fi < N_FADERS; fi++) {
        const FaderCfg *f = &FADERS[fi];
        if (f->channel != channel || f->cc != cc) continue;
        fader_current[fi] = value;
        fader_activated |= (1u << fi);
        cc_state_set(channel, cc, value);
        if (value < f->min_value) {
            fader_fill[fi] = 0;
            for (uint8_t i = 0; i < f->length; i++)
                set_led((uint8_t)((int)f->anchor_xy + i * f->pad_step), f->color_off);
        } else if (value >= f->max_value) {
            fader_fill[fi] = (uint8_t)(f->length - 1u);
            update_fader_leds(fi, (uint8_t)(f->length - 1u));
        } else {
            uint8_t best = 0, best_diff = 255;
            for (uint8_t t = 0; t < f->length; t++) {
                uint8_t cv = (t == 0) ? f->min_value :
                             (t >= f->length - 1u) ? f->max_value :
                             (uint8_t)(f->min_value + t * (f->max_value - f->min_value) / (f->length - 1u));
                uint8_t diff = (value >= cv) ? (value - cv) : (cv - value);
                if (diff < best_diff) { best_diff = diff; best = t; }
            }
            fader_fill[fi] = best;
            update_fader_leds(fi, best);
        }
    }
}

void mega_faders_init() {
    static uint8_t mode_initialized;
    if (!mode_initialized) {
        for (int i = 0; i < 100; i++) toggle[i] = 0;
        for (uint8_t i = 0; i < N_FADERS; i++) {
            fader_current[i] = FADERS[i].min_value;
            fader_fill[i] = 0;
        }
        fader_activated = 0;
        mode_initialized = 1;
    }
    set_led(11, toggle[11] ? 0xE039E0 : 0x220022);
    set_led(12, toggle[12] ? 0xE039E0 : 0x220022);
    set_led(13, toggle[13] ? 0xE039E0 : 0x220022);
    set_led(14, toggle[14] ? 0xE039E0 : 0x220022);
    set_led(19, 0x1A1A00);
    set_led(59, 0xFF8000);
    set_led(69, 0xB7FFB7);
    set_led(71, 0x041533);
    set_led(72, 0x041533);
    set_led(73, 0x041533);
    set_led(74, 0x041533);
    set_led(75, 0x041533);
    set_led(76, 0x041533);
    set_led(77, 0x041533);
    set_led(78, 0x041533);
    set_led(79, 0xB7B7FF);
    set_led(81, 0x0A1533);
    set_led(82, 0x0A1533);
    set_led(83, 0x0A1533);
    set_led(84, 0x0A1533);
    set_led(85, 0x0A1533);
    set_led(86, 0x0A1533);
    set_led(87, 0x0A1533);
    set_led(88, 0x0A1533);
    set_led(89, 0xFF7A7A);
    set_led(91, toggle[91] ? 0x04FF89 : 0x0A2211);
    set_led(92, toggle[92] ? 0x04FF89 : 0x0A2211);
    set_led(93, 0x331100);
    set_led(94, 0x331100);
    for (uint8_t i = 0; i < N_FADERS; i++) {
        uint8_t gv = cc_state_get(FADERS[i].channel, FADERS[i].cc);
        if (gv != 0xFF) {
            handle_fader_cc(FADERS[i].channel, FADERS[i].cc, gv);
        } else if (fader_activated & (1u << i)) {
            update_fader_leds(i, fader_fill[i]);
        } else {
            const FaderCfg *f = &FADERS[i];
            for (uint8_t j = 0; j < f->length; j++)
                set_led((uint8_t)((int)f->anchor_xy + j * f->pad_step), f->color_off);
        }
    }
}

void mega_faders_timer_event() { }

void mega_faders_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 11:
            if (type) {
                toggle[11] ^= 1;
                if (toggle[11]) {
                    send_midi3(0XB0, 20, 127);
                    set_led(11, 0xE039E0);
                } else {
                    send_midi3(0XB0, 20, 0);
                    set_led(11, 0x220022);
                }
            }
            break;
        case 12:
            if (type) {
                toggle[12] ^= 1;
                if (toggle[12]) {
                    send_midi3(0XB0, 21, 127);
                    set_led(12, 0xE039E0);
                } else {
                    send_midi3(0XB0, 21, 0);
                    set_led(12, 0x220022);
                }
            }
            break;
        case 13:
            if (type) {
                toggle[13] ^= 1;
                if (toggle[13]) {
                    send_midi3(0XB0, 22, 127);
                    set_led(13, 0xE039E0);
                } else {
                    send_midi3(0XB0, 22, 0);
                    set_led(13, 0x220022);
                }
            }
            break;
        case 14:
            if (type) {
                toggle[14] ^= 1;
                if (toggle[14]) {
                    send_midi3(0XB0, 23, 127);
                    set_led(14, 0xE039E0);
                } else {
                    send_midi3(0XB0, 23, 0);
                    set_led(14, 0x220022);
                }
            }
            break;
        case 19:
            if (type) {
                send_midi3(0XB0, 64, 127);
                set_led(19, 0xF3F306);
            } else {
                send_midi3(0XB0, 64, 0);
                set_led(19, 0x1A1A00);
            }
            break;
        case 59:
            if (type) mode_switch(MODE_MEGA_FADERS);
            break;
        case 69:
            if (type) mode_switch(MODE_D_FADE);
            break;
        case 71:
            if (type) {
                send_midi3(0X90, 48, value);
                set_led(71, 0x21A7D5);
            } else {
                send_midi3(0X90, 48, 0);
                set_led(71, 0x041533);
            }
            break;
        case 72:
            if (type) {
                send_midi3(0X90, 50, value);
                set_led(72, 0x21A7D5);
            } else {
                send_midi3(0X90, 50, 0);
                set_led(72, 0x041533);
            }
            break;
        case 73:
            if (type) {
                send_midi3(0X90, 52, value);
                set_led(73, 0x21A7D5);
            } else {
                send_midi3(0X90, 52, 0);
                set_led(73, 0x041533);
            }
            break;
        case 74:
            if (type) {
                send_midi3(0X90, 53, value);
                set_led(74, 0x21A7D5);
            } else {
                send_midi3(0X90, 53, 0);
                set_led(74, 0x041533);
            }
            break;
        case 75:
            if (type) {
                send_midi3(0X90, 55, value);
                set_led(75, 0x21A7D5);
            } else {
                send_midi3(0X90, 55, 0);
                set_led(75, 0x041533);
            }
            break;
        case 76:
            if (type) {
                send_midi3(0X90, 57, value);
                set_led(76, 0x21A7D5);
            } else {
                send_midi3(0X90, 57, 0);
                set_led(76, 0x041533);
            }
            break;
        case 77:
            if (type) {
                send_midi3(0X90, 59, value);
                set_led(77, 0x21A7D5);
            } else {
                send_midi3(0X90, 59, 0);
                set_led(77, 0x041533);
            }
            break;
        case 78:
            if (type) {
                send_midi3(0X90, 60, value);
                set_led(78, 0x21A7D5);
            } else {
                send_midi3(0X90, 60, 0);
                set_led(78, 0x041533);
            }
            break;
        case 79:
            if (type) mode_switch(MODE_MIXER2);
            break;
        case 81:
            if (type) {
                send_midi3(0X90, 60, value);
                set_led(81, 0x4488FF);
            } else {
                send_midi3(0X90, 60, 0);
                set_led(81, 0x0A1533);
            }
            break;
        case 82:
            if (type) {
                send_midi3(0X90, 62, value);
                set_led(82, 0x4488FF);
            } else {
                send_midi3(0X90, 62, 0);
                set_led(82, 0x0A1533);
            }
            break;
        case 83:
            if (type) {
                send_midi3(0X90, 64, value);
                set_led(83, 0x4488FF);
            } else {
                send_midi3(0X90, 64, 0);
                set_led(83, 0x0A1533);
            }
            break;
        case 84:
            if (type) {
                send_midi3(0X90, 65, value);
                set_led(84, 0x4488FF);
            } else {
                send_midi3(0X90, 65, 0);
                set_led(84, 0x0A1533);
            }
            break;
        case 85:
            if (type) {
                send_midi3(0X90, 67, value);
                set_led(85, 0x4488FF);
            } else {
                send_midi3(0X90, 67, 0);
                set_led(85, 0x0A1533);
            }
            break;
        case 86:
            if (type) {
                send_midi3(0X90, 69, value);
                set_led(86, 0x4488FF);
            } else {
                send_midi3(0X90, 69, 0);
                set_led(86, 0x0A1533);
            }
            break;
        case 87:
            if (type) {
                send_midi3(0X90, 71, value);
                set_led(87, 0x4488FF);
            } else {
                send_midi3(0X90, 71, 0);
                set_led(87, 0x0A1533);
            }
            break;
        case 88:
            if (type) {
                send_midi3(0X90, 72, value);
                set_led(88, 0x4488FF);
            } else {
                send_midi3(0X90, 72, 0);
                set_led(88, 0x0A1533);
            }
            break;
        case 89:
            if (type) mode_switch(MODE_MIXER1);
            break;
        case 91:
            if (type) {
                toggle[91] ^= 1;
                if (toggle[91]) {
                    send_midi3(0XB0, 64, 127);
                    set_led(91, 0x04FF89);
                } else {
                    send_midi3(0XB0, 64, 0);
                    set_led(91, 0x0A2211);
                }
            }
            break;
        case 92:
            if (type) {
                toggle[92] ^= 1;
                if (toggle[92]) {
                    send_midi3(0XB0, 65, 127);
                    set_led(92, 0x04FF89);
                } else {
                    send_midi3(0XB0, 65, 0);
                    set_led(92, 0x0A2211);
                }
            }
            break;
        case 93:
            if (type) {
                send_midi3(0XC0, 0, 0);
                set_led(93, 0xFF6633);
            } else {
                set_led(93, 0x331100);
            }
            break;
        case 94:
            if (type) {
                send_midi3(0XC0, 1, 0);
                set_led(94, 0xFF6633);
            } else {
                set_led(94, 0x331100);
            }
            break;
        default:
            if (type) {
                for (uint8_t fi = 0; fi < N_FADERS; fi++) {
                    const FaderCfg *f = &FADERS[fi];
                    int16_t delta = (int16_t)index - (int16_t)f->anchor_xy;
                    int8_t  step  = f->pad_step;
                    uint8_t throw_pos;
                    if (step > 0) {
                        if (delta < 0 || delta >= (int16_t)f->length * step || delta % step != 0) continue;
                        throw_pos = (uint8_t)(delta / step);
                    } else {
                        if (delta > 0 || delta <= (int16_t)f->length * step || (-delta) % (-step) != 0) continue;
                        throw_pos = (uint8_t)((-delta) / (-step));
                    }
                    uint8_t val = (throw_pos == 0) ? f->min_value :
                                  (throw_pos >= f->length - 1u) ? f->max_value :
                                  (uint8_t)(f->min_value + throw_pos * (f->max_value - f->min_value) / (f->length - 1u));
                    handle_fader_cc(f->channel, f->cc, val);
                    send_midi3((uint8_t)(0xB0 | f->channel), f->cc, val);
                    return;
                }
            }
            break;
    }
}

void mega_faders_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port;
    if ((status & 0xF0) == 0xB0)
        handle_fader_cc((uint8_t)(status & 0x0F), d1, d2);
}

void mega_faders_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
