/* mega_faders.c - generated by tools/json_to_mode.py */
#include <mode/user/mega_faders.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>

static void send_midi3(uint8_t status, uint8_t d1, uint8_t d2) {
    uint8_t buf[3] = { status, d1, d2 };
    driver_send_midi(1, buf, 3);
}

__attribute__((section(".cfw_bss"))) static uint8_t toggle[100];

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_value;
    uint8_t  max_value;
    uint32_t color_on;
    uint32_t color_off;
} FaderCfg;

#define N_FADERS 9
static const FaderCfg FADERS[N_FADERS] = {
    {
        .anchor_xy  = 21,
        .length     = 9,
        .pad_step   = 1,
        .cc         = 11,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0000FF,
        .color_off  = 0xB7B7FF,
    },
    {
        .anchor_xy  = 31,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 32,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 33,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 34,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 35,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 36,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 37,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
    {
        .anchor_xy  = 38,
        .length     = 4,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0xFFB7B7,
    },
};

__attribute__((section(".cfw_bss"))) static uint8_t fader_current[N_FADERS];
__attribute__((section(".cfw_bss"))) static uint8_t fader_fill[N_FADERS];

static void update_fader_leds(uint8_t fi, uint8_t fill) {
    const FaderCfg *f = &FADERS[fi];
    for (uint8_t i = 0; i < f->length; i++) {
        uint8_t pad = (uint8_t)((int)f->anchor_xy + i * f->pad_step);
        set_led(pad, (i <= fill) ? f->color_on : f->color_off);
    }
}

void mega_faders_init() {
    static uint8_t mode_initialized;
    if (!mode_initialized) {
        for (int i = 0; i < 100; i++) toggle[i] = 0;
        for (uint8_t i = 0; i < N_FADERS; i++) {
            fader_current[i] = FADERS[i].min_value;
            fader_fill[i] = 0;
            send_midi3((uint8_t)(0xB0 | FADERS[i].channel), FADERS[i].cc, FADERS[i].min_value);
        }
        mode_initialized = 1;
    }
    set_led(11, toggle[11] ? 0xE039E0 : 0x220022);
    set_led(12, toggle[12] ? 0xE039E0 : 0x220022);
    set_led(13, toggle[13] ? 0xE039E0 : 0x220022);
    set_led(14, toggle[14] ? 0xE039E0 : 0x220022);
    set_led(19, 0x1A1A00);
    set_led(59, 0x331100);
    set_led(69, 0x331100);
    set_led(71, 0x041533);
    set_led(72, 0x041533);
    set_led(73, 0x041533);
    set_led(74, 0x041533);
    set_led(75, 0x041533);
    set_led(76, 0x041533);
    set_led(77, 0x041533);
    set_led(78, 0x041533);
    set_led(79, toggle[79] ? 0x04FF89 : 0x0A2211);
    set_led(81, 0x0A1533);
    set_led(82, 0x0A1533);
    set_led(83, 0x0A1533);
    set_led(84, 0x0A1533);
    set_led(85, 0x0A1533);
    set_led(86, 0x0A1533);
    set_led(87, 0x0A1533);
    set_led(88, 0x0A1533);
    set_led(89, toggle[89] ? 0x04FF89 : 0x0A2211);
    set_led(95, 0x220033);
    set_led(96, 0x220033);
    set_led(97, 0x220033);
    set_led(98, 0x220033);
    for (uint8_t i = 0; i < N_FADERS; i++) update_fader_leds(i, fader_fill[i]);
}

void mega_faders_timer_event() { }

void mega_faders_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 11:
            if (type) {
                toggle[11] ^= 1;
                if (toggle[11]) {
                    send_midi3(0XB0, 20, 127);
                    set_led(11, 0xE039E0);
                } else {
                    send_midi3(0XB0, 20, 0);
                    set_led(11, 0x220022);
                }
            }
            break;
        case 12:
            if (type) {
                toggle[12] ^= 1;
                if (toggle[12]) {
                    send_midi3(0XB0, 21, 127);
                    set_led(12, 0xE039E0);
                } else {
                    send_midi3(0XB0, 21, 0);
                    set_led(12, 0x220022);
                }
            }
            break;
        case 13:
            if (type) {
                toggle[13] ^= 1;
                if (toggle[13]) {
                    send_midi3(0XB0, 22, 127);
                    set_led(13, 0xE039E0);
                } else {
                    send_midi3(0XB0, 22, 0);
                    set_led(13, 0x220022);
                }
            }
            break;
        case 14:
            if (type) {
                toggle[14] ^= 1;
                if (toggle[14]) {
                    send_midi3(0XB0, 23, 127);
                    set_led(14, 0xE039E0);
                } else {
                    send_midi3(0XB0, 23, 0);
                    set_led(14, 0x220022);
                }
            }
            break;
        case 19:
            if (type) {
                send_midi3(0XB0, 64, 127);
                set_led(19, 0xF3F306);
            } else {
                send_midi3(0XB0, 64, 0);
                set_led(19, 0x1A1A00);
            }
            break;
        case 59:
            if (type) {
                send_midi3(0XC0, 1, 0);
                set_led(59, 0xFF6633);
            } else {
                set_led(59, 0x331100);
            }
            break;
        case 69:
            if (type) {
                send_midi3(0XC0, 0, 0);
                set_led(69, 0xFF6633);
            } else {
                set_led(69, 0x331100);
            }
            break;
        case 71:
            if (type) {
                send_midi3(0X90, 48, value);
                set_led(71, 0x21A7D5);
            } else {
                send_midi3(0X90, 48, 0);
                set_led(71, 0x041533);
            }
            break;
        case 72:
            if (type) {
                send_midi3(0X90, 50, value);
                set_led(72, 0x21A7D5);
            } else {
                send_midi3(0X90, 50, 0);
                set_led(72, 0x041533);
            }
            break;
        case 73:
            if (type) {
                send_midi3(0X90, 52, value);
                set_led(73, 0x21A7D5);
            } else {
                send_midi3(0X90, 52, 0);
                set_led(73, 0x041533);
            }
            break;
        case 74:
            if (type) {
                send_midi3(0X90, 53, value);
                set_led(74, 0x21A7D5);
            } else {
                send_midi3(0X90, 53, 0);
                set_led(74, 0x041533);
            }
            break;
        case 75:
            if (type) {
                send_midi3(0X90, 55, value);
                set_led(75, 0x21A7D5);
            } else {
                send_midi3(0X90, 55, 0);
                set_led(75, 0x041533);
            }
            break;
        case 76:
            if (type) {
                send_midi3(0X90, 57, value);
                set_led(76, 0x21A7D5);
            } else {
                send_midi3(0X90, 57, 0);
                set_led(76, 0x041533);
            }
            break;
        case 77:
            if (type) {
                send_midi3(0X90, 59, value);
                set_led(77, 0x21A7D5);
            } else {
                send_midi3(0X90, 59, 0);
                set_led(77, 0x041533);
            }
            break;
        case 78:
            if (type) {
                send_midi3(0X90, 60, value);
                set_led(78, 0x21A7D5);
            } else {
                send_midi3(0X90, 60, 0);
                set_led(78, 0x041533);
            }
            break;
        case 79:
            if (type) {
                toggle[79] ^= 1;
                if (toggle[79]) {
                    send_midi3(0XB0, 65, 127);
                    set_led(79, 0x04FF89);
                } else {
                    send_midi3(0XB0, 65, 0);
                    set_led(79, 0x0A2211);
                }
            }
            break;
        case 81:
            if (type) {
                send_midi3(0X90, 60, value);
                set_led(81, 0x4488FF);
            } else {
                send_midi3(0X90, 60, 0);
                set_led(81, 0x0A1533);
            }
            break;
        case 82:
            if (type) {
                send_midi3(0X90, 62, value);
                set_led(82, 0x4488FF);
            } else {
                send_midi3(0X90, 62, 0);
                set_led(82, 0x0A1533);
            }
            break;
        case 83:
            if (type) {
                send_midi3(0X90, 64, value);
                set_led(83, 0x4488FF);
            } else {
                send_midi3(0X90, 64, 0);
                set_led(83, 0x0A1533);
            }
            break;
        case 84:
            if (type) {
                send_midi3(0X90, 65, value);
                set_led(84, 0x4488FF);
            } else {
                send_midi3(0X90, 65, 0);
                set_led(84, 0x0A1533);
            }
            break;
        case 85:
            if (type) {
                send_midi3(0X90, 67, value);
                set_led(85, 0x4488FF);
            } else {
                send_midi3(0X90, 67, 0);
                set_led(85, 0x0A1533);
            }
            break;
        case 86:
            if (type) {
                send_midi3(0X90, 69, value);
                set_led(86, 0x4488FF);
            } else {
                send_midi3(0X90, 69, 0);
                set_led(86, 0x0A1533);
            }
            break;
        case 87:
            if (type) {
                send_midi3(0X90, 71, value);
                set_led(87, 0x4488FF);
            } else {
                send_midi3(0X90, 71, 0);
                set_led(87, 0x0A1533);
            }
            break;
        case 88:
            if (type) {
                send_midi3(0X90, 72, value);
                set_led(88, 0x4488FF);
            } else {
                send_midi3(0X90, 72, 0);
                set_led(88, 0x0A1533);
            }
            break;
        case 89:
            if (type) {
                toggle[89] ^= 1;
                if (toggle[89]) {
                    send_midi3(0XB0, 64, 127);
                    set_led(89, 0x04FF89);
                } else {
                    send_midi3(0XB0, 64, 0);
                    set_led(89, 0x0A2211);
                }
            }
            break;
        case 95:
            if (type) mode_switch(MODE_MIXER1);
            break;
        case 96:
            if (type) mode_switch(MODE_MIXER2);
            break;
        case 97:
            if (type) mode_switch(MODE_MEGA_FADERS);
            break;
        case 98:
            if (type) mode_switch(MODE_MIX_TEST);
            break;
        case 21:
            if (type) {
                fader_current[0] = 0;
                fader_fill[0] = 0;
                update_fader_leds(0, 0);
                send_midi3(0XB0, 11, 0);
            }
            break;
        case 22:
            if (type) {
                fader_current[0] = 15;
                fader_fill[0] = 1;
                update_fader_leds(0, 1);
                send_midi3(0XB0, 11, 15);
            }
            break;
        case 23:
            if (type) {
                fader_current[0] = 31;
                fader_fill[0] = 2;
                update_fader_leds(0, 2);
                send_midi3(0XB0, 11, 31);
            }
            break;
        case 24:
            if (type) {
                fader_current[0] = 47;
                fader_fill[0] = 3;
                update_fader_leds(0, 3);
                send_midi3(0XB0, 11, 47);
            }
            break;
        case 25:
            if (type) {
                fader_current[0] = 63;
                fader_fill[0] = 4;
                update_fader_leds(0, 4);
                send_midi3(0XB0, 11, 63);
            }
            break;
        case 26:
            if (type) {
                fader_current[0] = 79;
                fader_fill[0] = 5;
                update_fader_leds(0, 5);
                send_midi3(0XB0, 11, 79);
            }
            break;
        case 27:
            if (type) {
                fader_current[0] = 95;
                fader_fill[0] = 6;
                update_fader_leds(0, 6);
                send_midi3(0XB0, 11, 95);
            }
            break;
        case 28:
            if (type) {
                fader_current[0] = 111;
                fader_fill[0] = 7;
                update_fader_leds(0, 7);
                send_midi3(0XB0, 11, 111);
            }
            break;
        case 29:
            if (type) {
                fader_current[0] = 127;
                fader_fill[0] = 8;
                update_fader_leds(0, 8);
                send_midi3(0XB0, 11, 127);
            }
            break;
        case 31:
            if (type) {
                fader_current[1] = 0;
                fader_fill[1] = 0;
                update_fader_leds(1, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 32:
            if (type) {
                fader_current[2] = 0;
                fader_fill[2] = 0;
                update_fader_leds(2, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 33:
            if (type) {
                fader_current[3] = 0;
                fader_fill[3] = 0;
                update_fader_leds(3, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 34:
            if (type) {
                fader_current[4] = 0;
                fader_fill[4] = 0;
                update_fader_leds(4, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 35:
            if (type) {
                fader_current[5] = 0;
                fader_fill[5] = 0;
                update_fader_leds(5, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 36:
            if (type) {
                fader_current[6] = 0;
                fader_fill[6] = 0;
                update_fader_leds(6, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 37:
            if (type) {
                fader_current[7] = 0;
                fader_fill[7] = 0;
                update_fader_leds(7, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 38:
            if (type) {
                fader_current[8] = 0;
                fader_fill[8] = 0;
                update_fader_leds(8, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 41:
            if (type) {
                fader_current[1] = 42;
                fader_fill[1] = 1;
                update_fader_leds(1, 1);
                send_midi3(0XB0, 0, 42);
            }
            break;
        case 42:
            if (type) {
                fader_current[2] = 42;
                fader_fill[2] = 1;
                update_fader_leds(2, 1);
                send_midi3(0XB0, 0, 42);
            }
            break;
        case 43:
            if (type) {
                fader_current[3] = 42;
                fader_fill[3] = 1;
                update_fader_leds(3, 1);
                send_midi3(0XB0, 0, 42);
            }
            break;
        case 44:
            if (type) {
                fader_current[4] = 42;
                fader_fill[4] = 1;
                update_fader_leds(4, 1);
                send_midi3(0XB0, 0, 42);
            }
            break;
        case 45:
            if (type) {
                fader_current[5] = 42;
                fader_fill[5] = 1;
                update_fader_leds(5, 1);
                send_midi3(0XB0, 0, 42);
            }
            break;
        case 46:
            if (type) {
                fader_current[6] = 42;
                fader_fill[6] = 1;
                update_fader_leds(6, 1);
                send_midi3(0XB0, 0, 42);
            }
            break;
        case 47:
            if (type) {
                fader_current[7] = 42;
                fader_fill[7] = 1;
                update_fader_leds(7, 1);
                send_midi3(0XB0, 0, 42);
            }
            break;
        case 48:
            if (type) {
                fader_current[8] = 42;
                fader_fill[8] = 1;
                update_fader_leds(8, 1);
                send_midi3(0XB0, 0, 42);
            }
            break;
        case 51:
            if (type) {
                fader_current[1] = 84;
                fader_fill[1] = 2;
                update_fader_leds(1, 2);
                send_midi3(0XB0, 0, 84);
            }
            break;
        case 52:
            if (type) {
                fader_current[2] = 84;
                fader_fill[2] = 2;
                update_fader_leds(2, 2);
                send_midi3(0XB0, 0, 84);
            }
            break;
        case 53:
            if (type) {
                fader_current[3] = 84;
                fader_fill[3] = 2;
                update_fader_leds(3, 2);
                send_midi3(0XB0, 0, 84);
            }
            break;
        case 54:
            if (type) {
                fader_current[4] = 84;
                fader_fill[4] = 2;
                update_fader_leds(4, 2);
                send_midi3(0XB0, 0, 84);
            }
            break;
        case 55:
            if (type) {
                fader_current[5] = 84;
                fader_fill[5] = 2;
                update_fader_leds(5, 2);
                send_midi3(0XB0, 0, 84);
            }
            break;
        case 56:
            if (type) {
                fader_current[6] = 84;
                fader_fill[6] = 2;
                update_fader_leds(6, 2);
                send_midi3(0XB0, 0, 84);
            }
            break;
        case 57:
            if (type) {
                fader_current[7] = 84;
                fader_fill[7] = 2;
                update_fader_leds(7, 2);
                send_midi3(0XB0, 0, 84);
            }
            break;
        case 58:
            if (type) {
                fader_current[8] = 84;
                fader_fill[8] = 2;
                update_fader_leds(8, 2);
                send_midi3(0XB0, 0, 84);
            }
            break;
        case 61:
            if (type) {
                fader_current[1] = 127;
                fader_fill[1] = 3;
                update_fader_leds(1, 3);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 62:
            if (type) {
                fader_current[2] = 127;
                fader_fill[2] = 3;
                update_fader_leds(2, 3);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 63:
            if (type) {
                fader_current[3] = 127;
                fader_fill[3] = 3;
                update_fader_leds(3, 3);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 64:
            if (type) {
                fader_current[4] = 127;
                fader_fill[4] = 3;
                update_fader_leds(4, 3);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 65:
            if (type) {
                fader_current[5] = 127;
                fader_fill[5] = 3;
                update_fader_leds(5, 3);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 66:
            if (type) {
                fader_current[6] = 127;
                fader_fill[6] = 3;
                update_fader_leds(6, 3);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 67:
            if (type) {
                fader_current[7] = 127;
                fader_fill[7] = 3;
                update_fader_leds(7, 3);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 68:
            if (type) {
                fader_current[8] = 127;
                fader_fill[8] = 3;
                update_fader_leds(8, 3);
                send_midi3(0XB0, 0, 127);
            }
            break;
        default: break;
    }
}

void mega_faders_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port; (void)status; (void)d1; (void)d2;
}

void mega_faders_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
