/* mix_test.c - generated by tools/json_to_mode.py */
#include <mode/user/mix_test.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>

static void send_midi3(uint8_t status, uint8_t d1, uint8_t d2) {
    uint8_t buf[3] = { status, d1, d2 };
    driver_send_midi(1, buf, 3);
}

__attribute__((section(".cfw_bss"))) static uint8_t toggle[100];

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_value;
    uint8_t  max_value;
    uint32_t color_on;
    uint32_t color_off;
} FaderCfg;

#define N_FADERS 5
static const FaderCfg FADERS[N_FADERS] = {
    {
        .anchor_xy  = 11,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0000,
        .color_off  = 0x480000,
    },
    {
        .anchor_xy  = 13,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0000FF,
        .color_off  = 0x000048,
    },
    {
        .anchor_xy  = 85,
        .length     = 8,
        .pad_step   = -10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x00FF00,
        .color_off  = 0x004800,
    },
    {
        .anchor_xy  = 87,
        .length     = 8,
        .pad_step   = -10,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x8000FF,
        .color_off  = 0x240048,
    },
    {
        .anchor_xy  = 94,
        .length     = 5,
        .pad_step   = 1,
        .cc         = 0,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x33CCCC,
        .color_off  = 0x0A2222,
    },
};

__attribute__((section(".cfw_bss"))) static uint8_t fader_current[N_FADERS];
__attribute__((section(".cfw_bss"))) static uint8_t fader_fill[N_FADERS];

static void update_fader_leds(uint8_t fi, uint8_t fill) {
    const FaderCfg *f = &FADERS[fi];
    for (uint8_t i = 0; i < f->length; i++) {
        uint8_t pad = (uint8_t)((int)f->anchor_xy + i * f->pad_step);
        set_led(pad, (i <= fill) ? f->color_on : f->color_off);
    }
}

void mix_test_init() {
    static uint8_t mode_initialized;
    if (!mode_initialized) {
        for (int i = 0; i < 100; i++) toggle[i] = 0;
        for (uint8_t i = 0; i < N_FADERS; i++) {
            fader_current[i] = FADERS[i].min_value;
            fader_fill[i] = 0;
            send_midi3((uint8_t)(0xB0 | FADERS[i].channel), FADERS[i].cc, FADERS[i].min_value);
        }
        mode_initialized = 1;
    }
    set_led(59, 0x482400);
    set_led(69, 0x004800);
    set_led(79, 0x000048);
    set_led(89, 0x480000);
    set_led(91, toggle[91] ? 0x4488FF : 0x0A1533);
    set_led(92, 0x0A2211);
    set_led(93, 0x331100);
    for (uint8_t i = 0; i < N_FADERS; i++) update_fader_leds(i, fader_fill[i]);
}

void mix_test_timer_event() { }

void mix_test_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 59:
            if (type) mode_switch(MODE_MIX_TEST);
            break;
        case 69:
            if (type) mode_switch(MODE_MEGA_FADERS);
            break;
        case 79:
            if (type) mode_switch(MODE_MIXER2);
            break;
        case 89:
            if (type) mode_switch(MODE_MIXER1);
            break;
        case 91:
            if (type) {
                toggle[91] ^= 1;
                if (toggle[91]) {
                    send_midi3(0X90, 60, 127);
                    set_led(91, 0x4488FF);
                } else {
                    send_midi3(0X90, 60, 0);
                    set_led(91, 0x0A1533);
                }
            }
            break;
        case 92:
            if (type) {
                send_midi3(0XB0, 0, 127);
                set_led(92, 0x44CC66);
            } else {
                set_led(92, 0x0A2211);
            }
            break;
        case 93:
            if (type) {
                send_midi3(0XC0, 0, 0);
                set_led(93, 0xFF6633);
            } else {
                set_led(93, 0x331100);
            }
            break;
        case 11:
            if (type) {
                fader_current[0] = 0;
                fader_fill[0] = 0;
                update_fader_leds(0, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 13:
            if (type) {
                fader_current[1] = 0;
                fader_fill[1] = 0;
                update_fader_leds(1, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 15:
            if (type) {
                fader_current[2] = 127;
                fader_fill[2] = 7;
                update_fader_leds(2, 7);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 17:
            if (type) {
                fader_current[3] = 127;
                fader_fill[3] = 7;
                update_fader_leds(3, 7);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 21:
            if (type) {
                fader_current[0] = 18;
                fader_fill[0] = 1;
                update_fader_leds(0, 1);
                send_midi3(0XB0, 0, 18);
            }
            break;
        case 23:
            if (type) {
                fader_current[1] = 18;
                fader_fill[1] = 1;
                update_fader_leds(1, 1);
                send_midi3(0XB0, 0, 18);
            }
            break;
        case 25:
            if (type) {
                fader_current[2] = 108;
                fader_fill[2] = 6;
                update_fader_leds(2, 6);
                send_midi3(0XB0, 0, 108);
            }
            break;
        case 27:
            if (type) {
                fader_current[3] = 108;
                fader_fill[3] = 6;
                update_fader_leds(3, 6);
                send_midi3(0XB0, 0, 108);
            }
            break;
        case 31:
            if (type) {
                fader_current[0] = 36;
                fader_fill[0] = 2;
                update_fader_leds(0, 2);
                send_midi3(0XB0, 0, 36);
            }
            break;
        case 33:
            if (type) {
                fader_current[1] = 36;
                fader_fill[1] = 2;
                update_fader_leds(1, 2);
                send_midi3(0XB0, 0, 36);
            }
            break;
        case 35:
            if (type) {
                fader_current[2] = 90;
                fader_fill[2] = 5;
                update_fader_leds(2, 5);
                send_midi3(0XB0, 0, 90);
            }
            break;
        case 37:
            if (type) {
                fader_current[3] = 90;
                fader_fill[3] = 5;
                update_fader_leds(3, 5);
                send_midi3(0XB0, 0, 90);
            }
            break;
        case 41:
            if (type) {
                fader_current[0] = 54;
                fader_fill[0] = 3;
                update_fader_leds(0, 3);
                send_midi3(0XB0, 0, 54);
            }
            break;
        case 43:
            if (type) {
                fader_current[1] = 54;
                fader_fill[1] = 3;
                update_fader_leds(1, 3);
                send_midi3(0XB0, 0, 54);
            }
            break;
        case 45:
            if (type) {
                fader_current[2] = 72;
                fader_fill[2] = 4;
                update_fader_leds(2, 4);
                send_midi3(0XB0, 0, 72);
            }
            break;
        case 47:
            if (type) {
                fader_current[3] = 72;
                fader_fill[3] = 4;
                update_fader_leds(3, 4);
                send_midi3(0XB0, 0, 72);
            }
            break;
        case 51:
            if (type) {
                fader_current[0] = 72;
                fader_fill[0] = 4;
                update_fader_leds(0, 4);
                send_midi3(0XB0, 0, 72);
            }
            break;
        case 53:
            if (type) {
                fader_current[1] = 72;
                fader_fill[1] = 4;
                update_fader_leds(1, 4);
                send_midi3(0XB0, 0, 72);
            }
            break;
        case 55:
            if (type) {
                fader_current[2] = 54;
                fader_fill[2] = 3;
                update_fader_leds(2, 3);
                send_midi3(0XB0, 0, 54);
            }
            break;
        case 57:
            if (type) {
                fader_current[3] = 54;
                fader_fill[3] = 3;
                update_fader_leds(3, 3);
                send_midi3(0XB0, 0, 54);
            }
            break;
        case 61:
            if (type) {
                fader_current[0] = 90;
                fader_fill[0] = 5;
                update_fader_leds(0, 5);
                send_midi3(0XB0, 0, 90);
            }
            break;
        case 63:
            if (type) {
                fader_current[1] = 90;
                fader_fill[1] = 5;
                update_fader_leds(1, 5);
                send_midi3(0XB0, 0, 90);
            }
            break;
        case 65:
            if (type) {
                fader_current[2] = 36;
                fader_fill[2] = 2;
                update_fader_leds(2, 2);
                send_midi3(0XB0, 0, 36);
            }
            break;
        case 67:
            if (type) {
                fader_current[3] = 36;
                fader_fill[3] = 2;
                update_fader_leds(3, 2);
                send_midi3(0XB0, 0, 36);
            }
            break;
        case 71:
            if (type) {
                fader_current[0] = 108;
                fader_fill[0] = 6;
                update_fader_leds(0, 6);
                send_midi3(0XB0, 0, 108);
            }
            break;
        case 73:
            if (type) {
                fader_current[1] = 108;
                fader_fill[1] = 6;
                update_fader_leds(1, 6);
                send_midi3(0XB0, 0, 108);
            }
            break;
        case 75:
            if (type) {
                fader_current[2] = 18;
                fader_fill[2] = 1;
                update_fader_leds(2, 1);
                send_midi3(0XB0, 0, 18);
            }
            break;
        case 77:
            if (type) {
                fader_current[3] = 18;
                fader_fill[3] = 1;
                update_fader_leds(3, 1);
                send_midi3(0XB0, 0, 18);
            }
            break;
        case 81:
            if (type) {
                fader_current[0] = 127;
                fader_fill[0] = 7;
                update_fader_leds(0, 7);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 83:
            if (type) {
                fader_current[1] = 127;
                fader_fill[1] = 7;
                update_fader_leds(1, 7);
                send_midi3(0XB0, 0, 127);
            }
            break;
        case 85:
            if (type) {
                fader_current[2] = 0;
                fader_fill[2] = 0;
                update_fader_leds(2, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 87:
            if (type) {
                fader_current[3] = 0;
                fader_fill[3] = 0;
                update_fader_leds(3, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 94:
            if (type) {
                fader_current[4] = 0;
                fader_fill[4] = 0;
                update_fader_leds(4, 0);
                send_midi3(0XB0, 0, 0);
            }
            break;
        case 95:
            if (type) {
                fader_current[4] = 31;
                fader_fill[4] = 1;
                update_fader_leds(4, 1);
                send_midi3(0XB0, 0, 31);
            }
            break;
        case 96:
            if (type) {
                fader_current[4] = 63;
                fader_fill[4] = 2;
                update_fader_leds(4, 2);
                send_midi3(0XB0, 0, 63);
            }
            break;
        case 97:
            if (type) {
                fader_current[4] = 95;
                fader_fill[4] = 3;
                update_fader_leds(4, 3);
                send_midi3(0XB0, 0, 95);
            }
            break;
        case 98:
            if (type) {
                fader_current[4] = 127;
                fader_fill[4] = 4;
                update_fader_leds(4, 4);
                send_midi3(0XB0, 0, 127);
            }
            break;
        default: break;
    }
    (void)value;
}

void mix_test_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port; (void)status; (void)d1; (void)d2;
}

void mix_test_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
