/* mixer2.c - generated by tools/json_to_mode.py */
#include <mode/user/mixer2.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>

static void send_midi3(uint8_t status, uint8_t d1, uint8_t d2) {
    uint8_t buf[3] = { status, d1, d2 };
    driver_send_midi(1, buf, 3);
}

__attribute__((section(".cfw_bss"))) static uint8_t toggle[100];

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_value;
    uint8_t  max_value;
    uint32_t color_on;
    uint32_t color_off;
} FaderCfg;

#define N_FADERS 8
static const FaderCfg FADERS[N_FADERS] = {
    {
        .anchor_xy  = 11,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 8,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0044FF,
        .color_off  = 0x001022,
    },
    {
        .anchor_xy  = 12,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 9,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0044FF,
        .color_off  = 0x001022,
    },
    {
        .anchor_xy  = 13,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 10,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0044FF,
        .color_off  = 0x001022,
    },
    {
        .anchor_xy  = 14,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 11,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0044FF,
        .color_off  = 0x001022,
    },
    {
        .anchor_xy  = 15,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 12,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0044FF,
        .color_off  = 0x001022,
    },
    {
        .anchor_xy  = 16,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 13,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0044FF,
        .color_off  = 0x001022,
    },
    {
        .anchor_xy  = 17,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 14,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0044FF,
        .color_off  = 0x001022,
    },
    {
        .anchor_xy  = 18,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 15,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x0044FF,
        .color_off  = 0x001022,
    },
};

__attribute__((section(".cfw_bss"))) static uint8_t fader_current[N_FADERS];
__attribute__((section(".cfw_bss"))) static uint8_t fader_fill[N_FADERS];

static void update_fader_leds(uint8_t fi, uint8_t fill) {
    const FaderCfg *f = &FADERS[fi];
    for (uint8_t i = 0; i < f->length; i++) {
        uint8_t pad = (uint8_t)((int)f->anchor_xy + i * f->pad_step);
        set_led(pad, (i <= fill) ? f->color_on : f->color_off);
    }
}

void mixer2_init() {
    static uint8_t mode_initialized;
    if (!mode_initialized) {
        for (int i = 0; i < 100; i++) toggle[i] = 0;
        for (uint8_t i = 0; i < N_FADERS; i++) {
            fader_current[i] = FADERS[i].min_value;
            fader_fill[i] = 0;
            send_midi3((uint8_t)(0xB0 | FADERS[i].channel), FADERS[i].cc, FADERS[i].min_value);
        }
        mode_initialized = 1;
    }
    set_led(59, 0x482400);
    set_led(69, 0x004800);
    set_led(79, 0x000048);
    set_led(89, 0x480000);
    set_led(91, toggle[91] ? 0xFFAA00 : 0x000000);
    set_led(92, toggle[92] ? 0xFFAA00 : 0x000000);
    set_led(93, toggle[93] ? 0xFFAA00 : 0x000000);
    set_led(94, toggle[94] ? 0xFFAA00 : 0x000000);
    set_led(95, toggle[95] ? 0xFFAA00 : 0x000000);
    set_led(96, toggle[96] ? 0xFFAA00 : 0x000000);
    set_led(97, toggle[97] ? 0xFFAA00 : 0x000000);
    set_led(98, toggle[98] ? 0xFFAA00 : 0x000000);
    for (uint8_t i = 0; i < N_FADERS; i++) update_fader_leds(i, fader_fill[i]);
}

void mixer2_timer_event() { }

void mixer2_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 59:
            if (type) mode_switch(MODE_MIX_TEST);
            break;
        case 69:
            if (type) mode_switch(MODE_MEGA_FADERS);
            break;
        case 79:
            if (type) mode_switch(MODE_MIXER2);
            break;
        case 89:
            if (type) mode_switch(MODE_MIXER1);
            break;
        case 91:
            if (type) {
                toggle[91] ^= 1;
                if (toggle[91]) {
                    send_midi3(0XB8, 20, 127);
                    set_led(91, 0xFFAA00);
                } else {
                    send_midi3(0XB8, 20, 0);
                    set_led(91, 0x000000);
                }
            }
            break;
        case 92:
            if (type) {
                toggle[92] ^= 1;
                if (toggle[92]) {
                    send_midi3(0XB9, 20, 127);
                    set_led(92, 0xFFAA00);
                } else {
                    send_midi3(0XB9, 20, 0);
                    set_led(92, 0x000000);
                }
            }
            break;
        case 93:
            if (type) {
                toggle[93] ^= 1;
                if (toggle[93]) {
                    send_midi3(0XBA, 20, 127);
                    set_led(93, 0xFFAA00);
                } else {
                    send_midi3(0XBA, 20, 0);
                    set_led(93, 0x000000);
                }
            }
            break;
        case 94:
            if (type) {
                toggle[94] ^= 1;
                if (toggle[94]) {
                    send_midi3(0XBB, 20, 127);
                    set_led(94, 0xFFAA00);
                } else {
                    send_midi3(0XBB, 20, 0);
                    set_led(94, 0x000000);
                }
            }
            break;
        case 95:
            if (type) {
                toggle[95] ^= 1;
                if (toggle[95]) {
                    send_midi3(0XBC, 20, 127);
                    set_led(95, 0xFFAA00);
                } else {
                    send_midi3(0XBC, 20, 0);
                    set_led(95, 0x000000);
                }
            }
            break;
        case 96:
            if (type) {
                toggle[96] ^= 1;
                if (toggle[96]) {
                    send_midi3(0XBD, 20, 127);
                    set_led(96, 0xFFAA00);
                } else {
                    send_midi3(0XBD, 20, 0);
                    set_led(96, 0x000000);
                }
            }
            break;
        case 97:
            if (type) {
                toggle[97] ^= 1;
                if (toggle[97]) {
                    send_midi3(0XBE, 20, 127);
                    set_led(97, 0xFFAA00);
                } else {
                    send_midi3(0XBE, 20, 0);
                    set_led(97, 0x000000);
                }
            }
            break;
        case 98:
            if (type) {
                toggle[98] ^= 1;
                if (toggle[98]) {
                    send_midi3(0XBF, 20, 127);
                    set_led(98, 0xFFAA00);
                } else {
                    send_midi3(0XBF, 20, 0);
                    set_led(98, 0x000000);
                }
            }
            break;
        case 11:
            if (type) {
                fader_current[0] = 0;
                fader_fill[0] = 0;
                update_fader_leds(0, 0);
                send_midi3(0XB8, 7, 0);
            }
            break;
        case 12:
            if (type) {
                fader_current[1] = 0;
                fader_fill[1] = 0;
                update_fader_leds(1, 0);
                send_midi3(0XB9, 7, 0);
            }
            break;
        case 13:
            if (type) {
                fader_current[2] = 0;
                fader_fill[2] = 0;
                update_fader_leds(2, 0);
                send_midi3(0XBA, 7, 0);
            }
            break;
        case 14:
            if (type) {
                fader_current[3] = 0;
                fader_fill[3] = 0;
                update_fader_leds(3, 0);
                send_midi3(0XBB, 7, 0);
            }
            break;
        case 15:
            if (type) {
                fader_current[4] = 0;
                fader_fill[4] = 0;
                update_fader_leds(4, 0);
                send_midi3(0XBC, 7, 0);
            }
            break;
        case 16:
            if (type) {
                fader_current[5] = 0;
                fader_fill[5] = 0;
                update_fader_leds(5, 0);
                send_midi3(0XBD, 7, 0);
            }
            break;
        case 17:
            if (type) {
                fader_current[6] = 0;
                fader_fill[6] = 0;
                update_fader_leds(6, 0);
                send_midi3(0XBE, 7, 0);
            }
            break;
        case 18:
            if (type) {
                fader_current[7] = 0;
                fader_fill[7] = 0;
                update_fader_leds(7, 0);
                send_midi3(0XBF, 7, 0);
            }
            break;
        case 21:
            if (type) {
                fader_current[0] = 18;
                fader_fill[0] = 1;
                update_fader_leds(0, 1);
                send_midi3(0XB8, 7, 18);
            }
            break;
        case 22:
            if (type) {
                fader_current[1] = 18;
                fader_fill[1] = 1;
                update_fader_leds(1, 1);
                send_midi3(0XB9, 7, 18);
            }
            break;
        case 23:
            if (type) {
                fader_current[2] = 18;
                fader_fill[2] = 1;
                update_fader_leds(2, 1);
                send_midi3(0XBA, 7, 18);
            }
            break;
        case 24:
            if (type) {
                fader_current[3] = 18;
                fader_fill[3] = 1;
                update_fader_leds(3, 1);
                send_midi3(0XBB, 7, 18);
            }
            break;
        case 25:
            if (type) {
                fader_current[4] = 18;
                fader_fill[4] = 1;
                update_fader_leds(4, 1);
                send_midi3(0XBC, 7, 18);
            }
            break;
        case 26:
            if (type) {
                fader_current[5] = 18;
                fader_fill[5] = 1;
                update_fader_leds(5, 1);
                send_midi3(0XBD, 7, 18);
            }
            break;
        case 27:
            if (type) {
                fader_current[6] = 18;
                fader_fill[6] = 1;
                update_fader_leds(6, 1);
                send_midi3(0XBE, 7, 18);
            }
            break;
        case 28:
            if (type) {
                fader_current[7] = 18;
                fader_fill[7] = 1;
                update_fader_leds(7, 1);
                send_midi3(0XBF, 7, 18);
            }
            break;
        case 31:
            if (type) {
                fader_current[0] = 36;
                fader_fill[0] = 2;
                update_fader_leds(0, 2);
                send_midi3(0XB8, 7, 36);
            }
            break;
        case 32:
            if (type) {
                fader_current[1] = 36;
                fader_fill[1] = 2;
                update_fader_leds(1, 2);
                send_midi3(0XB9, 7, 36);
            }
            break;
        case 33:
            if (type) {
                fader_current[2] = 36;
                fader_fill[2] = 2;
                update_fader_leds(2, 2);
                send_midi3(0XBA, 7, 36);
            }
            break;
        case 34:
            if (type) {
                fader_current[3] = 36;
                fader_fill[3] = 2;
                update_fader_leds(3, 2);
                send_midi3(0XBB, 7, 36);
            }
            break;
        case 35:
            if (type) {
                fader_current[4] = 36;
                fader_fill[4] = 2;
                update_fader_leds(4, 2);
                send_midi3(0XBC, 7, 36);
            }
            break;
        case 36:
            if (type) {
                fader_current[5] = 36;
                fader_fill[5] = 2;
                update_fader_leds(5, 2);
                send_midi3(0XBD, 7, 36);
            }
            break;
        case 37:
            if (type) {
                fader_current[6] = 36;
                fader_fill[6] = 2;
                update_fader_leds(6, 2);
                send_midi3(0XBE, 7, 36);
            }
            break;
        case 38:
            if (type) {
                fader_current[7] = 36;
                fader_fill[7] = 2;
                update_fader_leds(7, 2);
                send_midi3(0XBF, 7, 36);
            }
            break;
        case 41:
            if (type) {
                fader_current[0] = 54;
                fader_fill[0] = 3;
                update_fader_leds(0, 3);
                send_midi3(0XB8, 7, 54);
            }
            break;
        case 42:
            if (type) {
                fader_current[1] = 54;
                fader_fill[1] = 3;
                update_fader_leds(1, 3);
                send_midi3(0XB9, 7, 54);
            }
            break;
        case 43:
            if (type) {
                fader_current[2] = 54;
                fader_fill[2] = 3;
                update_fader_leds(2, 3);
                send_midi3(0XBA, 7, 54);
            }
            break;
        case 44:
            if (type) {
                fader_current[3] = 54;
                fader_fill[3] = 3;
                update_fader_leds(3, 3);
                send_midi3(0XBB, 7, 54);
            }
            break;
        case 45:
            if (type) {
                fader_current[4] = 54;
                fader_fill[4] = 3;
                update_fader_leds(4, 3);
                send_midi3(0XBC, 7, 54);
            }
            break;
        case 46:
            if (type) {
                fader_current[5] = 54;
                fader_fill[5] = 3;
                update_fader_leds(5, 3);
                send_midi3(0XBD, 7, 54);
            }
            break;
        case 47:
            if (type) {
                fader_current[6] = 54;
                fader_fill[6] = 3;
                update_fader_leds(6, 3);
                send_midi3(0XBE, 7, 54);
            }
            break;
        case 48:
            if (type) {
                fader_current[7] = 54;
                fader_fill[7] = 3;
                update_fader_leds(7, 3);
                send_midi3(0XBF, 7, 54);
            }
            break;
        case 51:
            if (type) {
                fader_current[0] = 72;
                fader_fill[0] = 4;
                update_fader_leds(0, 4);
                send_midi3(0XB8, 7, 72);
            }
            break;
        case 52:
            if (type) {
                fader_current[1] = 72;
                fader_fill[1] = 4;
                update_fader_leds(1, 4);
                send_midi3(0XB9, 7, 72);
            }
            break;
        case 53:
            if (type) {
                fader_current[2] = 72;
                fader_fill[2] = 4;
                update_fader_leds(2, 4);
                send_midi3(0XBA, 7, 72);
            }
            break;
        case 54:
            if (type) {
                fader_current[3] = 72;
                fader_fill[3] = 4;
                update_fader_leds(3, 4);
                send_midi3(0XBB, 7, 72);
            }
            break;
        case 55:
            if (type) {
                fader_current[4] = 72;
                fader_fill[4] = 4;
                update_fader_leds(4, 4);
                send_midi3(0XBC, 7, 72);
            }
            break;
        case 56:
            if (type) {
                fader_current[5] = 72;
                fader_fill[5] = 4;
                update_fader_leds(5, 4);
                send_midi3(0XBD, 7, 72);
            }
            break;
        case 57:
            if (type) {
                fader_current[6] = 72;
                fader_fill[6] = 4;
                update_fader_leds(6, 4);
                send_midi3(0XBE, 7, 72);
            }
            break;
        case 58:
            if (type) {
                fader_current[7] = 72;
                fader_fill[7] = 4;
                update_fader_leds(7, 4);
                send_midi3(0XBF, 7, 72);
            }
            break;
        case 61:
            if (type) {
                fader_current[0] = 90;
                fader_fill[0] = 5;
                update_fader_leds(0, 5);
                send_midi3(0XB8, 7, 90);
            }
            break;
        case 62:
            if (type) {
                fader_current[1] = 90;
                fader_fill[1] = 5;
                update_fader_leds(1, 5);
                send_midi3(0XB9, 7, 90);
            }
            break;
        case 63:
            if (type) {
                fader_current[2] = 90;
                fader_fill[2] = 5;
                update_fader_leds(2, 5);
                send_midi3(0XBA, 7, 90);
            }
            break;
        case 64:
            if (type) {
                fader_current[3] = 90;
                fader_fill[3] = 5;
                update_fader_leds(3, 5);
                send_midi3(0XBB, 7, 90);
            }
            break;
        case 65:
            if (type) {
                fader_current[4] = 90;
                fader_fill[4] = 5;
                update_fader_leds(4, 5);
                send_midi3(0XBC, 7, 90);
            }
            break;
        case 66:
            if (type) {
                fader_current[5] = 90;
                fader_fill[5] = 5;
                update_fader_leds(5, 5);
                send_midi3(0XBD, 7, 90);
            }
            break;
        case 67:
            if (type) {
                fader_current[6] = 90;
                fader_fill[6] = 5;
                update_fader_leds(6, 5);
                send_midi3(0XBE, 7, 90);
            }
            break;
        case 68:
            if (type) {
                fader_current[7] = 90;
                fader_fill[7] = 5;
                update_fader_leds(7, 5);
                send_midi3(0XBF, 7, 90);
            }
            break;
        case 71:
            if (type) {
                fader_current[0] = 108;
                fader_fill[0] = 6;
                update_fader_leds(0, 6);
                send_midi3(0XB8, 7, 108);
            }
            break;
        case 72:
            if (type) {
                fader_current[1] = 108;
                fader_fill[1] = 6;
                update_fader_leds(1, 6);
                send_midi3(0XB9, 7, 108);
            }
            break;
        case 73:
            if (type) {
                fader_current[2] = 108;
                fader_fill[2] = 6;
                update_fader_leds(2, 6);
                send_midi3(0XBA, 7, 108);
            }
            break;
        case 74:
            if (type) {
                fader_current[3] = 108;
                fader_fill[3] = 6;
                update_fader_leds(3, 6);
                send_midi3(0XBB, 7, 108);
            }
            break;
        case 75:
            if (type) {
                fader_current[4] = 108;
                fader_fill[4] = 6;
                update_fader_leds(4, 6);
                send_midi3(0XBC, 7, 108);
            }
            break;
        case 76:
            if (type) {
                fader_current[5] = 108;
                fader_fill[5] = 6;
                update_fader_leds(5, 6);
                send_midi3(0XBD, 7, 108);
            }
            break;
        case 77:
            if (type) {
                fader_current[6] = 108;
                fader_fill[6] = 6;
                update_fader_leds(6, 6);
                send_midi3(0XBE, 7, 108);
            }
            break;
        case 78:
            if (type) {
                fader_current[7] = 108;
                fader_fill[7] = 6;
                update_fader_leds(7, 6);
                send_midi3(0XBF, 7, 108);
            }
            break;
        case 81:
            if (type) {
                fader_current[0] = 127;
                fader_fill[0] = 7;
                update_fader_leds(0, 7);
                send_midi3(0XB8, 7, 127);
            }
            break;
        case 82:
            if (type) {
                fader_current[1] = 127;
                fader_fill[1] = 7;
                update_fader_leds(1, 7);
                send_midi3(0XB9, 7, 127);
            }
            break;
        case 83:
            if (type) {
                fader_current[2] = 127;
                fader_fill[2] = 7;
                update_fader_leds(2, 7);
                send_midi3(0XBA, 7, 127);
            }
            break;
        case 84:
            if (type) {
                fader_current[3] = 127;
                fader_fill[3] = 7;
                update_fader_leds(3, 7);
                send_midi3(0XBB, 7, 127);
            }
            break;
        case 85:
            if (type) {
                fader_current[4] = 127;
                fader_fill[4] = 7;
                update_fader_leds(4, 7);
                send_midi3(0XBC, 7, 127);
            }
            break;
        case 86:
            if (type) {
                fader_current[5] = 127;
                fader_fill[5] = 7;
                update_fader_leds(5, 7);
                send_midi3(0XBD, 7, 127);
            }
            break;
        case 87:
            if (type) {
                fader_current[6] = 127;
                fader_fill[6] = 7;
                update_fader_leds(6, 7);
                send_midi3(0XBE, 7, 127);
            }
            break;
        case 88:
            if (type) {
                fader_current[7] = 127;
                fader_fill[7] = 7;
                update_fader_leds(7, 7);
                send_midi3(0XBF, 7, 127);
            }
            break;
        default: break;
    }
    (void)value;
}

void mixer2_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port; (void)status; (void)d1; (void)d2;
}

void mixer2_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
