/* mixer2.c - generated by tools/json_to_mode.py */
#include <mode/user/mixer2.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>
#include <utils/cc_state.h>

static void send_midi3(uint8_t status, uint8_t d1, uint8_t d2) {
    uint8_t buf[3] = { status, d1, d2 };
    driver_send_midi(1, buf, 3);
}

__attribute__((section(".cfw_bss"))) static uint8_t toggle[100];

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_value;
    uint8_t  max_value;
    uint32_t color_on;
    uint32_t color_off;
} FaderCfg;

#define N_FADERS 8
static const FaderCfg FADERS[N_FADERS] = {
    {
        .anchor_xy  = 11,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 8,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x00FF00,
        .color_off  = 0xB7FFB7,
    },
    {
        .anchor_xy  = 12,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 9,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x00FF00,
        .color_off  = 0xB7FFB7,
    },
    {
        .anchor_xy  = 13,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 10,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x00FF00,
        .color_off  = 0xB7FFB7,
    },
    {
        .anchor_xy  = 14,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 11,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x00FF00,
        .color_off  = 0xB7FFB7,
    },
    {
        .anchor_xy  = 15,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 12,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF8000,
        .color_off  = 0xFFDBB7,
    },
    {
        .anchor_xy  = 16,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 13,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF8000,
        .color_off  = 0xFFDBB7,
    },
    {
        .anchor_xy  = 17,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 14,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF8000,
        .color_off  = 0xFFDBB7,
    },
    {
        .anchor_xy  = 18,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 15,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF8000,
        .color_off  = 0xFFDBB7,
    },
};

__attribute__((section(".cfw_bss"))) static uint8_t fader_current[N_FADERS];
__attribute__((section(".cfw_bss"))) static uint8_t fader_fill[N_FADERS];
__attribute__((section(".cfw_bss"))) static uint32_t fader_activated;

static void update_fader_leds(uint8_t fi, uint8_t fill) {
    const FaderCfg *f = &FADERS[fi];
    for (uint8_t i = 0; i < f->length; i++) {
        uint8_t pad = (uint8_t)((int)f->anchor_xy + i * f->pad_step);
        set_led(pad, (i <= fill) ? f->color_on : f->color_off);
    }
}

static void handle_fader_cc(uint8_t channel, uint8_t cc, uint8_t value) {
    for (uint8_t fi = 0; fi < N_FADERS; fi++) {
        const FaderCfg *f = &FADERS[fi];
        if (f->channel != channel || f->cc != cc) continue;
        fader_current[fi] = value;
        fader_activated |= (1u << fi);
        cc_state_set(channel, cc, value);
        if (value < f->min_value) {
            fader_fill[fi] = 0;
            for (uint8_t i = 0; i < f->length; i++)
                set_led((uint8_t)((int)f->anchor_xy + i * f->pad_step), f->color_off);
        } else if (value >= f->max_value) {
            fader_fill[fi] = (uint8_t)(f->length - 1u);
            update_fader_leds(fi, (uint8_t)(f->length - 1u));
        } else {
            uint8_t best = 0, best_diff = 255;
            for (uint8_t t = 0; t < f->length; t++) {
                uint8_t cv = (t == 0) ? f->min_value :
                             (t >= f->length - 1u) ? f->max_value :
                             (uint8_t)(f->min_value + t * (f->max_value - f->min_value) / (f->length - 1u));
                uint8_t diff = (value >= cv) ? (value - cv) : (cv - value);
                if (diff < best_diff) { best_diff = diff; best = t; }
            }
            fader_fill[fi] = best;
            update_fader_leds(fi, best);
        }
    }
}

void mixer2_init() {
    static uint8_t mode_initialized;
    if (!mode_initialized) {
        for (int i = 0; i < 100; i++) toggle[i] = 0;
        for (uint8_t i = 0; i < N_FADERS; i++) {
            fader_current[i] = FADERS[i].min_value;
            fader_fill[i] = 0;
        }
        fader_activated = 0;
        mode_initialized = 1;
    }
    set_led(59, 0xFFDBB7);
    set_led(69, 0xB7FFB7);
    set_led(79, 0x0000FF);
    set_led(89, 0xFFB7B7);
    set_led(91, toggle[91] ? 0xFFAA00 : 0x000000);
    set_led(92, toggle[92] ? 0xFFAA00 : 0x000000);
    set_led(93, toggle[93] ? 0xFFAA00 : 0x000000);
    set_led(94, toggle[94] ? 0xFFAA00 : 0x000000);
    set_led(95, toggle[95] ? 0xFFAA00 : 0x000000);
    set_led(96, toggle[96] ? 0xFFAA00 : 0x000000);
    set_led(97, toggle[97] ? 0xFFAA00 : 0x000000);
    set_led(98, toggle[98] ? 0xFFAA00 : 0x000000);
    for (uint8_t i = 0; i < N_FADERS; i++) {
        uint8_t gv = cc_state_get(FADERS[i].channel, FADERS[i].cc);
        if (gv != 0xFF) {
            handle_fader_cc(FADERS[i].channel, FADERS[i].cc, gv);
        } else if (fader_activated & (1u << i)) {
            update_fader_leds(i, fader_fill[i]);
        } else {
            const FaderCfg *f = &FADERS[i];
            for (uint8_t j = 0; j < f->length; j++)
                set_led((uint8_t)((int)f->anchor_xy + j * f->pad_step), f->color_off);
        }
    }
}

void mixer2_timer_event() { }

void mixer2_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 59:
            if (type) mode_switch(MODE_MEGA_FADERS);
            break;
        case 69:
            if (type) mode_switch(MODE_D_FADE);
            break;
        case 79:
            if (type) mode_switch(MODE_MIXER2);
            break;
        case 89:
            if (type) mode_switch(MODE_MIXER1);
            break;
        case 91:
            if (type) {
                toggle[91] ^= 1;
                if (toggle[91]) {
                    send_midi3(0XB8, 20, 127);
                    set_led(91, 0xFFAA00);
                } else {
                    send_midi3(0XB8, 20, 0);
                    set_led(91, 0x000000);
                }
            }
            break;
        case 92:
            if (type) {
                toggle[92] ^= 1;
                if (toggle[92]) {
                    send_midi3(0XB9, 20, 127);
                    set_led(92, 0xFFAA00);
                } else {
                    send_midi3(0XB9, 20, 0);
                    set_led(92, 0x000000);
                }
            }
            break;
        case 93:
            if (type) {
                toggle[93] ^= 1;
                if (toggle[93]) {
                    send_midi3(0XBA, 20, 127);
                    set_led(93, 0xFFAA00);
                } else {
                    send_midi3(0XBA, 20, 0);
                    set_led(93, 0x000000);
                }
            }
            break;
        case 94:
            if (type) {
                toggle[94] ^= 1;
                if (toggle[94]) {
                    send_midi3(0XBB, 20, 127);
                    set_led(94, 0xFFAA00);
                } else {
                    send_midi3(0XBB, 20, 0);
                    set_led(94, 0x000000);
                }
            }
            break;
        case 95:
            if (type) {
                toggle[95] ^= 1;
                if (toggle[95]) {
                    send_midi3(0XBC, 20, 127);
                    set_led(95, 0xFFAA00);
                } else {
                    send_midi3(0XBC, 20, 0);
                    set_led(95, 0x000000);
                }
            }
            break;
        case 96:
            if (type) {
                toggle[96] ^= 1;
                if (toggle[96]) {
                    send_midi3(0XBD, 20, 127);
                    set_led(96, 0xFFAA00);
                } else {
                    send_midi3(0XBD, 20, 0);
                    set_led(96, 0x000000);
                }
            }
            break;
        case 97:
            if (type) {
                toggle[97] ^= 1;
                if (toggle[97]) {
                    send_midi3(0XBE, 20, 127);
                    set_led(97, 0xFFAA00);
                } else {
                    send_midi3(0XBE, 20, 0);
                    set_led(97, 0x000000);
                }
            }
            break;
        case 98:
            if (type) {
                toggle[98] ^= 1;
                if (toggle[98]) {
                    send_midi3(0XBF, 20, 127);
                    set_led(98, 0xFFAA00);
                } else {
                    send_midi3(0XBF, 20, 0);
                    set_led(98, 0x000000);
                }
            }
            break;
        default:
            if (type) {
                for (uint8_t fi = 0; fi < N_FADERS; fi++) {
                    const FaderCfg *f = &FADERS[fi];
                    int16_t delta = (int16_t)index - (int16_t)f->anchor_xy;
                    int8_t  step  = f->pad_step;
                    uint8_t throw_pos;
                    if (step > 0) {
                        if (delta < 0 || delta >= (int16_t)f->length * step || delta % step != 0) continue;
                        throw_pos = (uint8_t)(delta / step);
                    } else {
                        if (delta > 0 || delta <= (int16_t)f->length * step || (-delta) % (-step) != 0) continue;
                        throw_pos = (uint8_t)((-delta) / (-step));
                    }
                    uint8_t val = (throw_pos == 0) ? f->min_value :
                                  (throw_pos >= f->length - 1u) ? f->max_value :
                                  (uint8_t)(f->min_value + throw_pos * (f->max_value - f->min_value) / (f->length - 1u));
                    handle_fader_cc(f->channel, f->cc, val);
                    send_midi3((uint8_t)(0xB0 | f->channel), f->cc, val);
                    return;
                }
            }
            break;
    }
    (void)value;
}

void mixer2_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port;
    if ((status & 0xF0) == 0xB0)
        handle_fader_cc((uint8_t)(status & 0x0F), d1, d2);
}

void mixer2_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
