/* one_fader.c - generated by tools/json_to_mode.py */
#include <mode/user/one_fader.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>

static uint8_t toggle[100];

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_value;
    uint8_t  max_value;
    uint32_t color_on;
    uint32_t color_off;
} FaderCfg;

#define N_FADERS 1
static const FaderCfg FADERS[N_FADERS] = {
    {
        .anchor_xy  = 31,
        .length     = 9,
        .pad_step   = 1,
        .cc         = 11,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xFF0100,
        .color_off  = 0xFF918C,
    },
};

static uint8_t fader_current[N_FADERS];

static void update_fader_leds(uint8_t fi, uint8_t cur) {
    const FaderCfg *f = &FADERS[fi];
    uint8_t fill = 0;
    uint8_t range = f->max_value - f->min_value;
    if (range > 0 && f->length > 1) {
        fill = (uint8_t)((uint16_t)(cur - f->min_value)
                         * (f->length - 1) / range);
    } else if (cur >= f->max_value) {
        fill = f->length > 0 ? f->length - 1 : 0;
    }
    for (uint8_t i = 0; i < f->length; i++) {
        uint8_t pad = (uint8_t)((int)f->anchor_xy + i * f->pad_step);
        set_led(pad, (i <= fill) ? f->color_on : f->color_off);
    }
}

void one_fader_init() {
    for (int i = 0; i < 100; i++) toggle[i] = 0;
    set_led(11, 0x220022);
    set_led(12, 0x220022);
    set_led(13, 0x220022);
    set_led(14, 0x220022);
    set_led(19, 0x1A1A00);
    set_led(59, 0x331100);
    set_led(69, 0x331100);
    set_led(71, 0x041533);
    set_led(72, 0x041533);
    set_led(73, 0x041533);
    set_led(74, 0x041533);
    set_led(75, 0x041533);
    set_led(76, 0x041533);
    set_led(77, 0x041533);
    set_led(78, 0x041533);
    set_led(79, 0x0A2211);
    set_led(81, 0x0A1533);
    set_led(82, 0x0A1533);
    set_led(83, 0x0A1533);
    set_led(84, 0x0A1533);
    set_led(85, 0x0A1533);
    set_led(86, 0x0A1533);
    set_led(87, 0x0A1533);
    set_led(88, 0x0A1533);
    set_led(89, 0x0A2211);
    for (uint8_t i = 0; i < N_FADERS; i++) {
        fader_current[i] = FADERS[i].min_value;
        update_fader_leds(i, fader_current[i]);
        driver_send_midi(1,
            (uint8_t[]){(uint8_t)(0xB0 | FADERS[i].channel),
                        FADERS[i].cc, FADERS[i].min_value}, 3);
    }
}

void one_fader_timer_event() { }

void one_fader_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 11:
            if (type) {
                toggle[11] ^= 1;
                if (toggle[11]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 20, 127}, 3);
                    set_led(11, 0xE039E0);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 20, 0}, 3);
                    set_led(11, 0x220022);
                }
            }
            break;
        case 12:
            if (type) {
                toggle[12] ^= 1;
                if (toggle[12]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 21, 127}, 3);
                    set_led(12, 0xE039E0);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 21, 0}, 3);
                    set_led(12, 0x220022);
                }
            }
            break;
        case 13:
            if (type) {
                toggle[13] ^= 1;
                if (toggle[13]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 22, 127}, 3);
                    set_led(13, 0xE039E0);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 22, 0}, 3);
                    set_led(13, 0x220022);
                }
            }
            break;
        case 14:
            if (type) {
                toggle[14] ^= 1;
                if (toggle[14]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 23, 127}, 3);
                    set_led(14, 0xE039E0);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 23, 0}, 3);
                    set_led(14, 0x220022);
                }
            }
            break;
        case 19:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0XB0, 64, 127}, 3);
                set_led(19, 0xF3F306);
            } else {
                driver_send_midi(1, (uint8_t[]){0XB0, 64, 0}, 3);
                set_led(19, 0x1A1A00);
            }
            break;
        case 59:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0XC0, 1, 0}, 3);
                set_led(59, 0xFF6633);
            }
            break;
        case 69:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0XC0, 0, 0}, 3);
                set_led(69, 0xFF6633);
            }
            break;
        case 71:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 48, value}, 3);
                set_led(71, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 48, 0}, 3);
                set_led(71, 0x041533);
            }
            break;
        case 72:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 50, value}, 3);
                set_led(72, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 50, 0}, 3);
                set_led(72, 0x041533);
            }
            break;
        case 73:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 52, value}, 3);
                set_led(73, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 52, 0}, 3);
                set_led(73, 0x041533);
            }
            break;
        case 74:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 53, value}, 3);
                set_led(74, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 53, 0}, 3);
                set_led(74, 0x041533);
            }
            break;
        case 75:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 55, value}, 3);
                set_led(75, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 55, 0}, 3);
                set_led(75, 0x041533);
            }
            break;
        case 76:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 57, value}, 3);
                set_led(76, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 57, 0}, 3);
                set_led(76, 0x041533);
            }
            break;
        case 77:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 59, value}, 3);
                set_led(77, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 59, 0}, 3);
                set_led(77, 0x041533);
            }
            break;
        case 78:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 60, value}, 3);
                set_led(78, 0x21A7D5);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 60, 0}, 3);
                set_led(78, 0x041533);
            }
            break;
        case 79:
            if (type) {
                toggle[79] ^= 1;
                if (toggle[79]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 65, 127}, 3);
                    set_led(79, 0x04FF89);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 65, 0}, 3);
                    set_led(79, 0x0A2211);
                }
            }
            break;
        case 81:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 60, value}, 3);
                set_led(81, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 60, 0}, 3);
                set_led(81, 0x0A1533);
            }
            break;
        case 82:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 62, value}, 3);
                set_led(82, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 62, 0}, 3);
                set_led(82, 0x0A1533);
            }
            break;
        case 83:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 64, value}, 3);
                set_led(83, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 64, 0}, 3);
                set_led(83, 0x0A1533);
            }
            break;
        case 84:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 65, value}, 3);
                set_led(84, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 65, 0}, 3);
                set_led(84, 0x0A1533);
            }
            break;
        case 85:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 67, value}, 3);
                set_led(85, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 67, 0}, 3);
                set_led(85, 0x0A1533);
            }
            break;
        case 86:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 69, value}, 3);
                set_led(86, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 69, 0}, 3);
                set_led(86, 0x0A1533);
            }
            break;
        case 87:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 71, value}, 3);
                set_led(87, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 71, 0}, 3);
                set_led(87, 0x0A1533);
            }
            break;
        case 88:
            if (type) {
                driver_send_midi(1, (uint8_t[]){0X90, 72, value}, 3);
                set_led(88, 0x4488FF);
            } else {
                driver_send_midi(1, (uint8_t[]){0X90, 72, 0}, 3);
                set_led(88, 0x0A1533);
            }
            break;
        case 89:
            if (type) {
                toggle[89] ^= 1;
                if (toggle[89]) {
                    driver_send_midi(1, (uint8_t[]){0XB0, 64, 127}, 3);
                    set_led(89, 0x04FF89);
                } else {
                    driver_send_midi(1, (uint8_t[]){0XB0, 64, 0}, 3);
                    set_led(89, 0x0A2211);
                }
            }
            break;
        case 31:
            if (type) {
                fader_current[0] = 0;
                update_fader_leds(0, 0);
                driver_send_midi(1, (uint8_t[]){0XB0, 11, 0}, 3);
            }
            break;
        case 32:
            if (type) {
                fader_current[0] = 15;
                update_fader_leds(0, 15);
                driver_send_midi(1, (uint8_t[]){0XB0, 11, 15}, 3);
            }
            break;
        case 33:
            if (type) {
                fader_current[0] = 31;
                update_fader_leds(0, 31);
                driver_send_midi(1, (uint8_t[]){0XB0, 11, 31}, 3);
            }
            break;
        case 34:
            if (type) {
                fader_current[0] = 47;
                update_fader_leds(0, 47);
                driver_send_midi(1, (uint8_t[]){0XB0, 11, 47}, 3);
            }
            break;
        case 35:
            if (type) {
                fader_current[0] = 63;
                update_fader_leds(0, 63);
                driver_send_midi(1, (uint8_t[]){0XB0, 11, 63}, 3);
            }
            break;
        case 36:
            if (type) {
                fader_current[0] = 79;
                update_fader_leds(0, 79);
                driver_send_midi(1, (uint8_t[]){0XB0, 11, 79}, 3);
            }
            break;
        case 37:
            if (type) {
                fader_current[0] = 95;
                update_fader_leds(0, 95);
                driver_send_midi(1, (uint8_t[]){0XB0, 11, 95}, 3);
            }
            break;
        case 38:
            if (type) {
                fader_current[0] = 111;
                update_fader_leds(0, 111);
                driver_send_midi(1, (uint8_t[]){0XB0, 11, 111}, 3);
            }
            break;
        case 39:
            if (type) {
                fader_current[0] = 127;
                update_fader_leds(0, 127);
                driver_send_midi(1, (uint8_t[]){0XB0, 11, 127}, 3);
            }
            break;
        default: break;
    }
}

void one_fader_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port; (void)status; (void)d1; (void)d2;
}

void one_fader_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
