/* showcase.c - generated by tools/json_to_mode.py */
#include <mode/user/showcase.h>
#include <mode/mode.h>
#include <led/led.h>
#include <driver/driver.h>

static void send_midi3(uint8_t status, uint8_t d1, uint8_t d2) {
    uint8_t buf[3] = { status, d1, d2 };
    driver_send_midi(1, buf, 3);
}

static uint8_t toggle[100];

typedef struct {
    uint8_t  anchor_xy;
    uint8_t  length;
    int8_t   pad_step;
    uint8_t  cc;
    uint8_t  channel;
    uint8_t  min_value;
    uint8_t  max_value;
    uint32_t color_on;
    uint32_t color_off;
} FaderCfg;

#define N_FADERS 2
static const FaderCfg FADERS[N_FADERS] = {
    {
        .anchor_xy  = 11,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 7,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0x22EEFF,
        .color_off  = 0x0A2233,
    },
    {
        .anchor_xy  = 12,
        .length     = 8,
        .pad_step   = 10,
        .cc         = 11,
        .channel    = 0,
        .min_value  = 0,
        .max_value  = 127,
        .color_on   = 0xCC44FF,
        .color_off  = 0x1A0033,
    },
};

static uint8_t fader_current[N_FADERS];
static uint8_t fader_fill[N_FADERS];

static void update_fader_leds(uint8_t fi, uint8_t fill) {
    const FaderCfg *f = &FADERS[fi];
    for (uint8_t i = 0; i < f->length; i++) {
        uint8_t pad = (uint8_t)((int)f->anchor_xy + i * f->pad_step);
        set_led(pad, (i <= fill) ? f->color_on : f->color_off);
    }
}

void showcase_init() {
    static uint8_t mode_initialized;
    if (!mode_initialized) {
        for (int i = 0; i < 100; i++) toggle[i] = 0;
        for (uint8_t i = 0; i < N_FADERS; i++) {
            fader_current[i] = FADERS[i].min_value;
            fader_fill[i] = 0;
            send_midi3((uint8_t)(0xB0 | FADERS[i].channel), FADERS[i].cc, FADERS[i].min_value);
        }
        mode_initialized = 1;
    }
    set_led(13, 0x330000);
    set_led(14, 0x1A0900);
    set_led(15, 0x1A1400);
    set_led(16, 0x060A22);
    set_led(17, 0x042211);
    set_led(18, 0x222233);
    set_led(19, 0x330004);
    set_led(23, 0x1A0600);
    set_led(24, 0x1A0408);
    set_led(25, 0x1A0414);
    set_led(26, 0x110018);
    set_led(27, 0x0D0418);
    set_led(28, 0x080014);
    set_led(29, 0x111133);
    set_led(33, 0x1A0011);
    set_led(34, 0x1A0014);
    set_led(35, 0x110022);
    set_led(36, 0x0A0522);
    set_led(37, 0x040A22);
    set_led(38, 0x041522);
    set_led(39, 0x1A0800);
    set_led(43, 0x000D22);
    set_led(44, toggle[44] ? 0xFFCC44 : 0x1A1608);
    set_led(45, toggle[45] ? 0xFF8844 : 0x1A0C08);
    set_led(46, toggle[46] ? 0xFF4488 : 0x1A0810);
    set_led(47, toggle[47] ? 0xCC44FF : 0x110022);
    set_led(48, toggle[48] ? 0x44FFAA : 0x061A10);
    set_led(49, 0x061522);
    set_led(53, 0x0D0033);
    set_led(54, 0x0D0033);
    set_led(55, 0x0D0033);
    set_led(56, 0x0D0033);
    set_led(57, 0x0D0033);
    set_led(58, toggle[58] ? 0xFF8800 : 0x1A0D00);
    set_led(59, toggle[59] ? 0x22FFDD : 0x041A16);
    set_led(63, 0x040822);
    set_led(64, 0x040822);
    set_led(65, 0x040822);
    set_led(66, 0x040822);
    set_led(67, 0x040822);
    set_led(68, toggle[68] ? 0x0099FF : 0x001522);
    set_led(69, toggle[69] ? 0x55FF88 : 0x081A0E);
    set_led(73, 0x001522);
    set_led(74, 0x001522);
    set_led(75, 0x001522);
    set_led(76, 0x001522);
    set_led(77, 0x001522);
    set_led(78, toggle[78] ? 0x00CCAA : 0x001A15);
    set_led(79, toggle[79] ? 0xFFAA00 : 0x1A1200);
    set_led(83, 0x001A16);
    set_led(84, 0x001A16);
    set_led(85, 0x001A16);
    set_led(86, 0x001A16);
    set_led(87, 0x001A16);
    set_led(88, toggle[88] ? 0x9900FF : 0x0D0022);
    set_led(89, 0x003308);
    set_led(91, 0x220500);
    set_led(92, 0x221500);
    set_led(93, 0x1A1A00);
    set_led(94, 0x042208);
    set_led(95, 0x002022);
    set_led(96, 0x040A22);
    set_led(97, 0x100022);
    set_led(98, 0x220018);
    for (uint8_t i = 0; i < N_FADERS; i++) update_fader_leds(i, fader_fill[i]);
}

void showcase_timer_event() { }

void showcase_surface_event(uint8_t type, uint8_t index, uint8_t value) {
    switch (index) {
        case 13:
            if (type) {
                send_midi3(0XB0, 120, 0);
                set_led(13, 0xFF0000);
            } else {
                send_midi3(0XB0, 120, 0);
                set_led(13, 0x330000);
            }
            break;
        case 14:
            if (type) {
                send_midi3(0XB0, 121, 0);
                set_led(14, 0xFF6600);
            } else {
                send_midi3(0XB0, 121, 0);
                set_led(14, 0x1A0900);
            }
            break;
        case 15:
            if (type) {
                send_midi3(0XB0, 123, 0);
                set_led(15, 0xFFEE00);
            } else {
                send_midi3(0XB0, 123, 0);
                set_led(15, 0x1A1400);
            }
            break;
        case 16:
            if (type) {
                send_midi3(0XB0, 1, 0);
                set_led(16, 0x4488FF);
            } else {
                send_midi3(0XB0, 1, 0);
                set_led(16, 0x060A22);
            }
            break;
        case 17:
            if (type) {
                send_midi3(0XB0, 64, 0);
                set_led(17, 0x22FF66);
            } else {
                send_midi3(0XB0, 64, 0);
                set_led(17, 0x042211);
            }
            break;
        case 18:
            if (type) mode_switch(1);
            break;
        case 19:
            if (type) {
                send_midi3(0XB0, 120, 0);
                set_led(19, 0xFF0022);
            } else {
                send_midi3(0XB0, 120, 0);
                set_led(19, 0x330004);
            }
            break;
        case 23:
            if (type) {
                send_midi3(0XC0, 9, 0);
                set_led(23, 0xFF4422);
            }
            break;
        case 24:
            if (type) {
                send_midi3(0XC0, 10, 0);
                set_led(24, 0xFF2255);
            }
            break;
        case 25:
            if (type) {
                send_midi3(0XC0, 11, 0);
                set_led(25, 0xFF22AA);
            }
            break;
        case 26:
            if (type) {
                send_midi3(0XC0, 12, 0);
                set_led(26, 0xCC22DD);
            }
            break;
        case 27:
            if (type) {
                send_midi3(0XC0, 13, 0);
                set_led(27, 0x8822CC);
            }
            break;
        case 28:
            if (type) {
                send_midi3(0XC0, 14, 0);
                set_led(28, 0x5522BB);
            }
            break;
        case 29:
            if (type) mode_switch(0);
            break;
        case 33:
            if (type) {
                send_midi3(0XB0, 16, 127);
                set_led(33, 0xFF2255);
            } else {
                send_midi3(0XB0, 16, 0);
                set_led(33, 0x1A0011);
            }
            break;
        case 34:
            if (type) {
                send_midi3(0XB0, 17, 127);
                set_led(34, 0xFF22BB);
            } else {
                send_midi3(0XB0, 17, 0);
                set_led(34, 0x1A0014);
            }
            break;
        case 35:
            if (type) {
                send_midi3(0XB0, 18, 127);
                set_led(35, 0xCC22FF);
            } else {
                send_midi3(0XB0, 18, 0);
                set_led(35, 0x110022);
            }
            break;
        case 36:
            if (type) {
                send_midi3(0XB0, 19, 127);
                set_led(36, 0x6622FF);
            } else {
                send_midi3(0XB0, 19, 0);
                set_led(36, 0x0A0522);
            }
            break;
        case 37:
            if (type) {
                send_midi3(0XB0, 20, 127);
                set_led(37, 0x2266FF);
            } else {
                send_midi3(0XB0, 20, 0);
                set_led(37, 0x040A22);
            }
            break;
        case 38:
            if (type) {
                send_midi3(0XB0, 21, 127);
                set_led(38, 0x22CCFF);
            } else {
                send_midi3(0XB0, 21, 0);
                set_led(38, 0x041522);
            }
            break;
        case 39:
            if (type) {
                send_midi3(0XC0, 8, 0);
                set_led(39, 0xFF6622);
            }
            break;
        case 43:
            if (type) {
                send_midi3(0XB0, 1, 127);
                set_led(43, 0x0077FF);
            } else {
                send_midi3(0XB0, 1, 0);
                set_led(43, 0x000D22);
            }
            break;
        case 44:
            if (type) {
                toggle[44] ^= 1;
                if (toggle[44]) {
                    send_midi3(0XB0, 71, 127);
                    set_led(44, 0xFFCC44);
                } else {
                    send_midi3(0XB0, 71, 0);
                    set_led(44, 0x1A1608);
                }
            }
            break;
        case 45:
            if (type) {
                toggle[45] ^= 1;
                if (toggle[45]) {
                    send_midi3(0XB0, 73, 127);
                    set_led(45, 0xFF8844);
                } else {
                    send_midi3(0XB0, 73, 0);
                    set_led(45, 0x1A0C08);
                }
            }
            break;
        case 46:
            if (type) {
                toggle[46] ^= 1;
                if (toggle[46]) {
                    send_midi3(0XB0, 72, 127);
                    set_led(46, 0xFF4488);
                } else {
                    send_midi3(0XB0, 72, 0);
                    set_led(46, 0x1A0810);
                }
            }
            break;
        case 47:
            if (type) {
                toggle[47] ^= 1;
                if (toggle[47]) {
                    send_midi3(0XB0, 10, 127);
                    set_led(47, 0xCC44FF);
                } else {
                    send_midi3(0XB0, 10, 64);
                    set_led(47, 0x110022);
                }
            }
            break;
        case 48:
            if (type) {
                toggle[48] ^= 1;
                if (toggle[48]) {
                    send_midi3(0XB0, 68, 127);
                    set_led(48, 0x44FFAA);
                } else {
                    send_midi3(0XB0, 68, 0);
                    set_led(48, 0x061A10);
                }
            }
            break;
        case 49:
            if (type) {
                send_midi3(0XB0, 2, 127);
                set_led(49, 0x44AAFF);
            } else {
                send_midi3(0XB0, 2, 0);
                set_led(49, 0x061522);
            }
            break;
        case 53:
            if (type) {
                send_midi3(0X90, 36, value);
                set_led(53, 0x8822FF);
            } else {
                send_midi3(0X90, 36, 0);
                set_led(53, 0x0D0033);
            }
            break;
        case 54:
            if (type) {
                send_midi3(0X90, 39, value);
                set_led(54, 0x8822FF);
            } else {
                send_midi3(0X90, 39, 0);
                set_led(54, 0x0D0033);
            }
            break;
        case 55:
            if (type) {
                send_midi3(0X90, 41, value);
                set_led(55, 0x8822FF);
            } else {
                send_midi3(0X90, 41, 0);
                set_led(55, 0x0D0033);
            }
            break;
        case 56:
            if (type) {
                send_midi3(0X90, 43, value);
                set_led(56, 0x8822FF);
            } else {
                send_midi3(0X90, 43, 0);
                set_led(56, 0x0D0033);
            }
            break;
        case 57:
            if (type) {
                send_midi3(0X90, 46, value);
                set_led(57, 0x8822FF);
            } else {
                send_midi3(0X90, 46, 0);
                set_led(57, 0x0D0033);
            }
            break;
        case 58:
            if (type) {
                toggle[58] ^= 1;
                if (toggle[58]) {
                    send_midi3(0XB0, 74, 127);
                    set_led(58, 0xFF8800);
                } else {
                    send_midi3(0XB0, 74, 0);
                    set_led(58, 0x1A0D00);
                }
            }
            break;
        case 59:
            if (type) {
                toggle[59] ^= 1;
                if (toggle[59]) {
                    send_midi3(0XB0, 66, 127);
                    set_led(59, 0x22FFDD);
                } else {
                    send_midi3(0XB0, 66, 0);
                    set_led(59, 0x041A16);
                }
            }
            break;
        case 63:
            if (type) {
                send_midi3(0X90, 48, value);
                set_led(63, 0x2244FF);
            } else {
                send_midi3(0X90, 48, 0);
                set_led(63, 0x040822);
            }
            break;
        case 64:
            if (type) {
                send_midi3(0X90, 51, value);
                set_led(64, 0x2244FF);
            } else {
                send_midi3(0X90, 51, 0);
                set_led(64, 0x040822);
            }
            break;
        case 65:
            if (type) {
                send_midi3(0X90, 53, value);
                set_led(65, 0x2244FF);
            } else {
                send_midi3(0X90, 53, 0);
                set_led(65, 0x040822);
            }
            break;
        case 66:
            if (type) {
                send_midi3(0X90, 55, value);
                set_led(66, 0x2244FF);
            } else {
                send_midi3(0X90, 55, 0);
                set_led(66, 0x040822);
            }
            break;
        case 67:
            if (type) {
                send_midi3(0X90, 58, value);
                set_led(67, 0x2244FF);
            } else {
                send_midi3(0X90, 58, 0);
                set_led(67, 0x040822);
            }
            break;
        case 68:
            if (type) {
                toggle[68] ^= 1;
                if (toggle[68]) {
                    send_midi3(0XB0, 94, 127);
                    set_led(68, 0x0099FF);
                } else {
                    send_midi3(0XB0, 94, 0);
                    set_led(68, 0x001522);
                }
            }
            break;
        case 69:
            if (type) {
                toggle[69] ^= 1;
                if (toggle[69]) {
                    send_midi3(0XB0, 67, 127);
                    set_led(69, 0x55FF88);
                } else {
                    send_midi3(0XB0, 67, 0);
                    set_led(69, 0x081A0E);
                }
            }
            break;
        case 73:
            if (type) {
                send_midi3(0X90, 60, value);
                set_led(73, 0x00AAFF);
            } else {
                send_midi3(0X90, 60, 0);
                set_led(73, 0x001522);
            }
            break;
        case 74:
            if (type) {
                send_midi3(0X90, 63, value);
                set_led(74, 0x00AAFF);
            } else {
                send_midi3(0X90, 63, 0);
                set_led(74, 0x001522);
            }
            break;
        case 75:
            if (type) {
                send_midi3(0X90, 65, value);
                set_led(75, 0x00AAFF);
            } else {
                send_midi3(0X90, 65, 0);
                set_led(75, 0x001522);
            }
            break;
        case 76:
            if (type) {
                send_midi3(0X90, 67, value);
                set_led(76, 0x00AAFF);
            } else {
                send_midi3(0X90, 67, 0);
                set_led(76, 0x001522);
            }
            break;
        case 77:
            if (type) {
                send_midi3(0X90, 70, value);
                set_led(77, 0x00AAFF);
            } else {
                send_midi3(0X90, 70, 0);
                set_led(77, 0x001522);
            }
            break;
        case 78:
            if (type) {
                toggle[78] ^= 1;
                if (toggle[78]) {
                    send_midi3(0XB0, 93, 127);
                    set_led(78, 0x00CCAA);
                } else {
                    send_midi3(0XB0, 93, 0);
                    set_led(78, 0x001A15);
                }
            }
            break;
        case 79:
            if (type) {
                toggle[79] ^= 1;
                if (toggle[79]) {
                    send_midi3(0XB0, 65, 127);
                    set_led(79, 0xFFAA00);
                } else {
                    send_midi3(0XB0, 65, 0);
                    set_led(79, 0x1A1200);
                }
            }
            break;
        case 83:
            if (type) {
                send_midi3(0X90, 72, value);
                set_led(83, 0x00FFCC);
            } else {
                send_midi3(0X90, 72, 0);
                set_led(83, 0x001A16);
            }
            break;
        case 84:
            if (type) {
                send_midi3(0X90, 75, value);
                set_led(84, 0x00FFCC);
            } else {
                send_midi3(0X90, 75, 0);
                set_led(84, 0x001A16);
            }
            break;
        case 85:
            if (type) {
                send_midi3(0X90, 77, value);
                set_led(85, 0x00FFCC);
            } else {
                send_midi3(0X90, 77, 0);
                set_led(85, 0x001A16);
            }
            break;
        case 86:
            if (type) {
                send_midi3(0X90, 79, value);
                set_led(86, 0x00FFCC);
            } else {
                send_midi3(0X90, 79, 0);
                set_led(86, 0x001A16);
            }
            break;
        case 87:
            if (type) {
                send_midi3(0X90, 82, value);
                set_led(87, 0x00FFCC);
            } else {
                send_midi3(0X90, 82, 0);
                set_led(87, 0x001A16);
            }
            break;
        case 88:
            if (type) {
                toggle[88] ^= 1;
                if (toggle[88]) {
                    send_midi3(0XB0, 91, 127);
                    set_led(88, 0x9900FF);
                } else {
                    send_midi3(0XB0, 91, 0);
                    set_led(88, 0x0D0022);
                }
            }
            break;
        case 89:
            if (type) {
                send_midi3(0XB0, 64, 127);
                set_led(89, 0x00FF44);
            } else {
                send_midi3(0XB0, 64, 0);
                set_led(89, 0x003308);
            }
            break;
        case 91:
            if (type) {
                send_midi3(0XC0, 0, 0);
                set_led(91, 0xFF2200);
            }
            break;
        case 92:
            if (type) {
                send_midi3(0XC0, 1, 0);
                set_led(92, 0xFF8800);
            }
            break;
        case 93:
            if (type) {
                send_midi3(0XC0, 2, 0);
                set_led(93, 0xEEFF00);
            }
            break;
        case 94:
            if (type) {
                send_midi3(0XC0, 3, 0);
                set_led(94, 0x22FF44);
            }
            break;
        case 95:
            if (type) {
                send_midi3(0XC0, 4, 0);
                set_led(95, 0x00EEFF);
            }
            break;
        case 96:
            if (type) {
                send_midi3(0XC0, 5, 0);
                set_led(96, 0x2266FF);
            }
            break;
        case 97:
            if (type) {
                send_midi3(0XC0, 6, 0);
                set_led(97, 0x8800FF);
            }
            break;
        case 98:
            if (type) {
                send_midi3(0XC0, 7, 0);
                set_led(98, 0xFF00CC);
            }
            break;
        case 11:
            if (type) {
                fader_current[0] = 0;
                fader_fill[0] = 0;
                update_fader_leds(0, 0);
                send_midi3(0XB0, 7, 0);
            }
            break;
        case 12:
            if (type) {
                fader_current[1] = 0;
                fader_fill[1] = 0;
                update_fader_leds(1, 0);
                send_midi3(0XB0, 11, 0);
            }
            break;
        case 21:
            if (type) {
                fader_current[0] = 18;
                fader_fill[0] = 1;
                update_fader_leds(0, 1);
                send_midi3(0XB0, 7, 18);
            }
            break;
        case 22:
            if (type) {
                fader_current[1] = 18;
                fader_fill[1] = 1;
                update_fader_leds(1, 1);
                send_midi3(0XB0, 11, 18);
            }
            break;
        case 31:
            if (type) {
                fader_current[0] = 36;
                fader_fill[0] = 2;
                update_fader_leds(0, 2);
                send_midi3(0XB0, 7, 36);
            }
            break;
        case 32:
            if (type) {
                fader_current[1] = 36;
                fader_fill[1] = 2;
                update_fader_leds(1, 2);
                send_midi3(0XB0, 11, 36);
            }
            break;
        case 41:
            if (type) {
                fader_current[0] = 54;
                fader_fill[0] = 3;
                update_fader_leds(0, 3);
                send_midi3(0XB0, 7, 54);
            }
            break;
        case 42:
            if (type) {
                fader_current[1] = 54;
                fader_fill[1] = 3;
                update_fader_leds(1, 3);
                send_midi3(0XB0, 11, 54);
            }
            break;
        case 51:
            if (type) {
                fader_current[0] = 72;
                fader_fill[0] = 4;
                update_fader_leds(0, 4);
                send_midi3(0XB0, 7, 72);
            }
            break;
        case 52:
            if (type) {
                fader_current[1] = 72;
                fader_fill[1] = 4;
                update_fader_leds(1, 4);
                send_midi3(0XB0, 11, 72);
            }
            break;
        case 61:
            if (type) {
                fader_current[0] = 90;
                fader_fill[0] = 5;
                update_fader_leds(0, 5);
                send_midi3(0XB0, 7, 90);
            }
            break;
        case 62:
            if (type) {
                fader_current[1] = 90;
                fader_fill[1] = 5;
                update_fader_leds(1, 5);
                send_midi3(0XB0, 11, 90);
            }
            break;
        case 71:
            if (type) {
                fader_current[0] = 108;
                fader_fill[0] = 6;
                update_fader_leds(0, 6);
                send_midi3(0XB0, 7, 108);
            }
            break;
        case 72:
            if (type) {
                fader_current[1] = 108;
                fader_fill[1] = 6;
                update_fader_leds(1, 6);
                send_midi3(0XB0, 11, 108);
            }
            break;
        case 81:
            if (type) {
                fader_current[0] = 127;
                fader_fill[0] = 7;
                update_fader_leds(0, 7);
                send_midi3(0XB0, 7, 127);
            }
            break;
        case 82:
            if (type) {
                fader_current[1] = 127;
                fader_fill[1] = 7;
                update_fader_leds(1, 7);
                send_midi3(0XB0, 11, 127);
            }
            break;
        default: break;
    }
}

void showcase_midi_event(uint8_t port, uint8_t status, uint8_t d1, uint8_t d2) {
    (void)port; (void)status; (void)d1; (void)d2;
}

void showcase_aftertouch_event(uint8_t index, uint8_t value) {
    (void)index; (void)value;
}
